### ISSUE TITLE
Applies not called when using the built in websocket system

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/fluffos#1012]
I have a sneaking suspicion that applies like terminal_type()  (https://www.fluffos.info/apply/interactive/terminal_type.html) and window_wize() (https://www.fluffos.info/apply/interactive/window_size.html) are never called when using the FluffOS built in web-socket mechanism? Can anybody confirm? It kind of makes the default demo suck when the mudlib cannot auto detect terminal and window sizes?

Could the websocket identity itself as a websocket connection using terminal_type() Is it possible for it to call window_size() initially and upon size changes as well?

**Comment by thefallentree** [comment]
Right now it doesn't: because Websocket implementation uses "ascii" sub protocol, which has no support for telnet sequence. 

we can add a "telnet" subprotocol that properly handles telnet over websocket, but I havn't made any progress on it yet

**Comment by tsathoqqua** [comment]
Is this connected to #840 ?

**Comment by thefallentree** [comment]
duplicated of #840

**Comment by icewolfz** [comment]
I sent a pull request (https://github.com/fluffos/fluffos/pull/1097) that adds websocket binary protocol that adds telnet support, while leaving the old ASCII protocol as well, just do new WebSocket(url, 'binary'); and it should work like the old 2.x websocket, you will just need a javascript telnet layer to decode the data and handle it. I also have a fork that has it already merged in my repo
