### ISSUE TITLE
How to cast class types?

### ISSUE THREAD

**Issue by virthe** [fluffos/fluffos#1066]
Normally when using classes in eval (when the class type is unknown) the compiler will guess which class to use based on which variable types the class has.

In a situation when two classes have a shared member variable but different structures there can be situations where the compiler cannot guess which class to use and it throws an error.  The error tells me to use casting to tell the compiler which class to use. However I cannot find any instructions on how to cast class type variables.

Here is a minimal command to reproduce the issue:
```
//cmd to cause class cast error

inherit CMD;

class Foo {
   int a;
   string cool_var;
}

class Bar {
   string cool_var;
}


void data_setter(mixed m, string data) {
   m -> cool_var = data;
}


void main() {
   mixed m = new(class Bar, cool_var: "old data");

   write("Class cast test:\n");
   
   evaluate((: data_setter, m, "new data":));

   printf("Data = %s\n", m -> cool_var);
}
```

The compiler is unable to determine which class to use and gives this error:
```
update classcast
## ------- /wiz/virthe/cmds/classcast.c:16
## More than one class in scope has member 'cool_var'; use a cast to
disambiguate.
  m -> cool_var = data
                    ^

## ------- /wiz/virthe/cmds/classcast.c:27
## More than one class in scope has member 'cool_var'; use a cast to
disambiguate.
  printf("Data = %s\n", m -> cool_var)
```

I have tried various combinations of brackets but nothing I try will cast the class var.

Thanks for your help and apologies if I have missed something in the documentation.

Driver version: fluffos 20240114-1ec4ec37-uncommited

**Comment by virthe** [comment]
This is what I expect should work based on the docs but still gets a compiler error:

```
## ------- /wiz/virthe/cmds/classcast.c:27
## More than one class in scope has member 'cool_var'; use a cast to
disambiguate.
  printf("Data = %s\n", (class Bar)m -> cool_var)
  ```

**Comment by virthe** [comment]
I figured out the syntax:
```
//cmd to cause class cast error

inherit CMD;

class Foo {
   int a;
   string cool_var;
}

class Bar {
   string cool_var;
}


void data_setter(mixed m, string data) {
   ((class Bar)m)  -> cool_var = data;
}


void main() {
   mixed m = new(class Bar, cool_var: "old data");

   write("Class cast test:\n");
   
   evaluate((: data_setter, m, "new data":));

   printf("Data = %s\n", ((class Bar)m) -> cool_var);
}
```

Needed to add an extra () around everything.  `((class Bar) m) -> cool_var`

I can add an example of this syntax to:  https://github.com/fluffos/fluffos/blob/master/docs/lpc/types/classes.md

So that future coders may read it and know.

**Comment by michaelprograms** [comment]
This issue can be closed since Classes documentation was updated.
