### ISSUE TITLE
Rewrite file related operation using  C++, with automatic CRLF handling.

### ISSUE THREAD

**Issue by thefallentree** [fluffos/fluffos#248]
http://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf?answertab=votes#tab-top

**Comment by quixadhal** [comment]
I assume this only applies to files opened in non-binary mode?  One of the
tricks I've seen a few muds do is to open and manipulate gif files for map
data, which of course relies on being able to get byte-for-byte
compatibility.

I personally wouldn't use stream I/O for such a task, but I'm not a big C++
guy, so I don't know if others might try it.  For myself, I'd rather link
in libpng with an extension API and expose that. :)

**Comment by thefallentree** [comment]
@quixadhal  Only read_file is affected, read_bytes() efun is not effected.

**Comment by quixadhal** [comment]
Cool.  Sounds like a good idea then! :)
