### ISSUE TITLE
missing feature

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#285]
I'm missing a feature present in the old 3.2 driver:
There it was possible to adjust the include path from within the mudlib.
This could be used e.g. for adding domain/region (what ever you call it) specific include dirs if and only if the loaded object resides within this domain…
Like:

path to object | include path
-------- | --------
/obj/f1.c | "/include"
/Domain/a/obj/f2.c | "/Domain/a/include:/include"
/Domaih/b/obj/f3.c | "/Domain/b/include:/include"
/secure/daemon/finger.c | "/secure/include"

For those who don't know the old driver:
This was accomplished by setting various driver_hooks ('unnamed applies', one of them relevant for the include_path), some of them had to be set, others could be set.

I don't believe it would be too dificult to change a configuration option to take either a simple string "/inc_dir1:/inc_dir2" or the name of a function within the master "get_inc_dir()".
In the latter case said function would get appropriate arguments (like path of object to be loaded) and return the value to be used (like include path).
There might be other such hooks which could be useful, but this was the one I noticed…

**Comment by quixadhal** [comment]
Never knew about that as a driver thing.  I remember doing a workaround bit
of code for my own areas to help make it easier to move things between
different domains.

static void create() {
    string this_area = "";
...
    this_area = implode(rexplode(file_name(this_object()), "/")[0..<3],
"/");
...
    SetExits( ([
                "north" : this_area + "/rooms/kitchen",
                "south" : this_area + "/rooms/back_room",
                "east" : this_area + "/rooms/hallway1",
                "west" : "/realms/quixadhal/workroom",
                ]) );
    SetDoor("west", this_area + "/doors/common_room");
}

But I can see how a domain specific include path could make overrides much
easier.

**Comment by Shea690901** [comment]
Here is the relevant documentation from the current ldmud-driver:
[include_dirs driver hook](/ldmud/ldmud/tree/master/doc/hook/include_dirs)
But it was also present in the amylaar driver…
And it's not only useful for some overrides, just think about a _huge_ domain, with a lot of include files…
It would be nice for such a thing to use
```c
#include <file1.h>
#include <file2.h>
…
#include <filen.h>
```
instead of
```c
#include "/full/domain/path/file1.h"
#include "/full/domain/path/file2.h"
…
#include "/full/domain/path/filen.h"
```

I've also just taken a look into the other hooks:

[hook](/ldmud/ldmud/tree/master/doc/hook) | present in fluffos | usefulness
--- | --- | ---
auto_include | global include file | definitly
clean_up | - | what for? Just take a single name (clean_up)
clone_uids | master::creator_file() | depends on desired security model
command | process_input() ? | sounds good to me
create_clone | - | see clean_up
create_ob | - | don't know… is it neccessary to have different initializers for cloning or loading?
create_super | - | and another one, this time for inherits, questionable…
default_method | - | could be useful in giving warnings about future removal of 'standard' functions
default_prompt | - | imho unneccessary
erq_stop | - | useless without erqd (external request demon, used for external commands)
include_dirs | include directories (partial only) | full support could be very useful ;)
load_uids | master::creator_file() | does one need two different functions?
modify_command* | - | sounds fishy (possible security hole) to me
move_object* | sefun::move_object | why this way, when I can use a simul efun?
msg_discarded | - | do the message efuns (tell_obuect, write, …) throw errors? If not: could be useful…
no_echo | - | is this something the mudlib should/needs to know?
no_ipc_slot | - | useless as long as there is no 'maximum users', there after it's just a config option
notify_fail | - | never truly needed, standard notify_fail is more than enough…
print_prompt | - | ??? what for?
regexp_package | - | IF better as either compile time option or multiple packages with corresponding efun names…
reset | - | see clean_up
send_notify_fail | - | could be useful for different communi
telnet_neg | - | telnet nevotiations within the mudlib?

**Comment by thefallentree** [comment]
I'm a bit confused,  by hook you mean master applies?  can you give a example of how you are going to use this hook?   I imagine it will be 

```
set_include_dirs(new);
load_object(xxxx);
set_include_dirs(old);
```

**Comment by Shea690901** [comment]
In a way those hooks were applies which didn't got a static name but a number instead, then at runtime the master would tell the driver which function/string/what_ever to use instead of that number…
The include dirs driver hook got called as soon as the parser found a include directive within the source, meaning that I wouldn't have to set the path myself in front of the load_object, but the load_object itself would initiate the correct setting of the include path…
You might want to take a look at [MorgenGrauen's master.c](https://github.com/Shea690901/MorgenGrauen/blob/master/secure/master.c) (ldmud). In line 98 it sets the hook for include dir's…
Sadly it doesn't use the full feature, instead of a static string one **may** use a function which returns a string:
```c
set_driver_hook(H_INCLUDE_DIRS, "generate_include_path");
```
and then something like (this function wouldn't work under ldmud!!!):
```c
string generate_include_path(string file)
{
    string *path = explode(file, "/");
    if(path[1] == "Domains")
        return implode(path[0..2], "/") + "/include:/include";
    else
        return "/include";
}
```
Of course it would be posible to realy micromanage this path:
Wizards get their own include pathes: "/players/wiz/include:/include", if they are members of some domain those objects would get something like: "/Domains/domain/members/wiz/include:/Domains/domain/include:/include" and daemons and the simul_efuns won't look into "/include" at all: "/secure/include"

For the ldmud driver (I don't remember for the old amylaar or the CD drivers) this function had to do the search itself and return the full pathname of the include file to be used!!!
E.g. ```get_include_file("std.h", "/obj/weapon.c")``` would return "/include/std.h" and ```get_include_file("std.h", "/Domains/domain/obj/special_weapon.c")``` would return "/Domains/domain/include/generic.h".
But IMHO that's too much work for the mudlib…
This hook got called for **each include file** of each object! I do believe it would be enough it got called **once** for each object, returning the search path to be used for this object, like I've done in my example above alas, the driver already is fully capable of searching itself…
