### ISSUE TITLE
#pragma

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#294]
lex.h defines following pragmas:
strict_types, warnings, save_types, save_binary, optimize, error_context and optimize_high

lex.cc uses:
strict_types, warnings, save_types, optimize and error_context

What happend to save_binary and optimize_high?

**Comment by thefallentree** [comment]
save_binary was ripped out during Fluffos 2.x, because it was claimed it was broken.

optimize_high i think was never finished, also ripped out.

**Comment by thefallentree** [comment]
due to compatibility reasons I think we need to still accept existing pragmas

**Comment by Shea690901** [comment]
Just curious what happend, but you're right they should still be accepted, even when they do nothing…

**Comment by thefallentree** [comment]
You should be able to fish it out from the git history. we have all the way tracing back to mudos!

**Comment by Shea690901** [comment]
Not exactly what I meant (your answer was it already), but still good to know :)
