### ISSUE TITLE
<bug>(packages/matrix & packages/dwlib)

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#303]
Both packages won't compile with missing include file std.h.
Both use ```../base/std.h``` instead of ```../../base/std.h```…
Both are also using at least one include file which no longer exist: ```lpc_incl.h``` (haven't looked further)…

Since it's rather low priority for me, I haven't looked when it went away and what it did contain.
The one thing I did was grep and the only other references left are some comment's, mostly in other include files stating kt would be better to include this file instead of the other ones which probably means it got somewhere down the road renamed to ```base/package_api.h```

**Comment by thefallentree** [comment]
yes, all package got rewritted, and dwlib and matrix are the ones no one use, so no one touched them.

**Comment by Shea690901** [comment]
Then perhaps they should get removed?

**Comment by thefallentree** [comment]
matrix seems useful to be kept alive. DWLIB i have no idea.

**Comment by Shea690901** [comment]
As fas as I've seen matrix seems rather specialized…
If we keep matrix, which I'm a friend of for otherwise I wouldn't have noticed the bug in the first place, perhaps a more general package?

**Comment by quixadhal** [comment]
dwlib is specifically things that the folks at Discworld use.  Removing
things that you guys don't use is ensuring that people using those mudlibs
will never be able to adopt your newer version of the driver.

**Comment by thefallentree** [comment]
They haven't been using it for awhile , PACKAGE in general I think should
be owned by package owner, we can keep the files, but fixing them is done
by driver people in best effort only.

**Comment by Shea690901** [comment]
Ok…
