### ISSUE TITLE
Possible bug with restore_object()

### ISSUE THREAD

**Issue by virosh** [fluffos/fluffos#332]
Hello All,

I am having the following issue after compiling the latest git sources - the restore_object() function just stopped working and it is impossible to login due to this as the password check always fails.
I made a small log dump during the restore function which writes some of the user's variables in order to check if it's restored and here is the result with the old driver version (commit 8a231002334758e321d31cb24a9679b40c916e8a):
`Debug restored object is: OBJ(/adm/master/login#1), Name is: test, Password is: REDACTED, Characters are: ([ "test" : "/std/user", "gargamel" : "/std/user" ]).`
However, here is the output of the same function from the latest driver (commit 473687a3c1f5f57069cea10585efa1f40df5575a):
`Debug restored object is: OBJ(/adm/master/login#1), Name is: logon, Password is: 0, Characters are: UNDEFINED.`

Before finding this i was trying to figure out which function in the security system i broke as i am currently redesigning it, but found that even if i provide full permissions to anyone the object is still not restored. After that i started building the FluffOS driver by checking out every commit backwards until it worked.

I am not sure if this is really a bug or something was changed internally and was not documented but decided to submit it anyway.

Cheers,
Ves

**Comment by quixadhal** [comment]
Just a sanity check.... did you double check that the file itself was being
saved correctly?  I could see either side being an issue, if the new
version saves it incorrectly, or if scoping rules have changed so "nosave"
is now the default when not explicitly declared otherwise.

**Comment by virosh** [comment]
The file is correct. It is not touched (written) by the new driver, however it cannot be loaded. The restore ends successfully but the object is empty and i am out of ideas how to dig further into this.
About the scoping rules - how can i check this? I know how to declare "nosave" but i have no idea how  to declare it "save" if for some reason the scope has changed.

Cheers,
Ves

**Comment by thefallentree** [comment]
Yes, there has been report on the save issue too, see #334  , which hasn't been resolved yet. I advise using  the latest tagged version for now.

**Comment by virosh** [comment]
Thanks!
I will keep an eye on this thread.
