### ISSUE TITLE
Adding more people into project

### ISSUE THREAD

**Issue by thefallentree** [fluffos/fluffos#342]
Now that Github support branch review-only protect, I'm willing to add more people to the project, 

Here's is the initial list
@Shea690901  

@dwwodan  if you want , i can add you too!

**Comment by Shea690901** [comment]
First: sorry for the long delay...
My tablet broke and I just now got a replacement (sadly, as of yet ,on loan only)...

Second: While I´m honored to be considered as a team member, I´m not sure that I´ll have the time :(
