### ISSUE TITLE
Document compat busters with older muds and mudlibs 

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#348]
There should be some sort of list somewhere indicating how well fluffos 3.0 works with older mudlibs and muds that ran on the 2.x series. I assume there are some compat busters it would be nice to know what they are.

**Comment by cartercheng** [comment]
I was looking over the latest dead souls 3.8.6 release and the sefun object doesn't compile under the latest fluffos driver taken directly from the repo.

**Comment by thefallentree** [comment]
What is exactly the issue here? can you post it? 

The main problem right now, is the SENSIBLE_MODIFIER , AFAIK

**Comment by cartercheng** [comment]
What is SENSIBLE_MODIFIER? It would be nice to have some documentation on exactly what needs to be changed even if it's just a few short sentences or paragraphs. The error I am getting after fixing one of the array reserved word errors is-

/secure/sefun/communications.c line 36: syntax error before  tc_color_logic(stri

**Comment by Shea690901** [comment]
Depending on SENSIBLE_MODIFIER ´static´might not exist as keyword...
Take a look at fluffos´ local_options-file and search for SENSIBLE_MODIFIER

**Comment by cartercheng** [comment]
Yes I actually managed to get ds mostly working or enough working that I am sure it is possible to do so. However I spoke with Cratylus the maintainer and he is not willing to distribute a copy with the array reserved word taken out so it's all for naught.

**Comment by thefallentree** [comment]
If he is willing to let me export the content of the old driver forum into
new discourse forum , I am willing to add back the array keyword for it :-)

**Comment by cartercheng** [comment]
I think he is somewhat unwilling to make any changes. You can try talking to him. I think we might need to continue to rely on the old lpmuds.net download page even though the forums remain down. There is a public domain version of dead souls which can be modified though but it 2.x versus 3.x

**Comment by seikichin** [comment]
/*
 * local_options.h: compile-time configuration of the driver
 */

/****************************************************************************
 * EVERY time you change ANYTHING in this file, RECOMPILE from scratch.     *
 * (type "make clean" then "make" on a UNIX system) Failure to do so may    *
 * cause the driver to behave oddly.                                        *
 ****************************************************************************/

/* NOTES: Many of the configurable options are now set in the runtime config.
 * 
 * This file only contain a list of default settings, for quick diffing .
 * See detailed explaination from 'local_options.README'
 */

#ifndef _LOCAL_OPTIONS_H_
#define _LOCAL_OPTIONS_H_

/****************************************************************************
 *                              COMPAT                                      *
 ****************************************************************************/
#undef NO_ADD_ACTION
#undef NO_SNOOP
#undef NO_ENVIRONMENT
#define NO_WIZARDS
#define NO_LIGHT
#undef OLD_ED
#undef ED_INDENT_CASE
#define ED_INDENT_SPACES 4
#undef ED_USE_TABS
#define ED_TAB_WIDTH 8
#undef RECEIVE_ED
#define RESTRICTED_ED
#undef SENSIBLE_MODIFIERS
#define MUDLIB_ERROR_HANDLER
#define NO_RESETS
#undef LAZY_RESETS
#define INTERACTIVE_CATCH_TELL
#define REF_RESERVED_WORD
/****************************************************************************
 *                           MISCELLANEOUS                                  *
 ****************************************************************************/
#define CUSTOM_CRYPT
#undef COMPAT_32
#define DEFAULT_PRAGMAS 0
#define SAVE_EXTENSION ".o"
#undef PRIVS
#undef NO_SHADOWS
#undef USE_ICONV
#undef IPV6
#undef DTRACE
#define PRIVS
#define ARRAY_RESERVED_WORD
#define  OPCPROF
/****************************************************************************
 *                              PACKAGES                                    *
 ****************************************************************************/
#define PACKAGE_OPS
#define PACKAGE_CORE

#define PACKAGE_CONTRIB
#define PACKAGE_DEVELOP
#define PACKAGE_MATH
#define PACKAGE_MATRIX
#define PACKAGE_MUDLIB_STATS
#define PACKAGE_SOCKETS
#define PACKAGE_PARSER
#define PACKAGE_EXTERNAL
#undef PACKAGE_DB
#ifdef PACKAGE_DB
#undef USE_MYSQL 1
#undef MYSQL_SOCKET_ADDRESS    "/var/lib/mysql/mysql.sock"
#undef USE_MSQL
#undef USE_POSTGRES
#undef USE_SQLITE3
#undef DEFAULT_DB  USE_MYSQL
#endif
#define PACKAGE_ASYNC
#define PACKAGE_SHA1
#define PACKAGE_CRYPTO
#define PACKAGE_TRIM
#define PACKAGE_PCRE
#undef PACKAGE_DWLIB
#undef PACKAGE_UIDS
//#ifdef PACKAGE_UIDS
#undef AUTO_SETEUID
#define AUTO_TRUST_BACKBONE
//#endif
#define PACKAGE_COMPRESS
#define SAVE_GZ_EXTENSION ".o.gz"
#undef PACKAGE_THREAD

//#define PACKAGE_ANSI
//#define PACKAGE_ARITH_OPERATOR
//#define PACKAGE_CHINESE
//#define PACKAGE_DATABASE
//#undef PACKAGE_MAPPINGBASE
#endif /* _LOCAL_OPTIONS_H_ */

you can use this local_options to drive Dead Souls 3.8.6  Driver: FluffOS 3.0.20170907

**Comment by seikichin** [comment]
change  \lib\secure\daemon\master.c line 66      to   ->     //opcprof(opfile);  
efun opcprof longer exist so you have to comment out  "\lib\secure\daemon\master.c" line 66 
then the lib can run

**Comment by thefallentree** [comment]
I guess the only big thing is SENSIBLE_MODIFIER.  which I hope someone can document it.
