### ISSUE TITLE
Problems with array reserved word removal.

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#349]
My understanding is this particular feature of the mudos/fluffos line has been removed but I would like to see it back since no simple text substitution currently can easily replace it since it means two different things in the language depending on context:

1) array c; // this is a valid statement and one has to substitute mixed * for it if array is removed.
2) int array b; // this is also a valid statement and one has to substitute * for it if array is removed.

Finding all such instances is non trivial for a mud admin and breaks compat with many existing mudlibs including dead-souls(foundation and NM), lpuni, I believe lima and perhaps even discworld.

**Comment by Shea690901** [comment]
I think the LDMud "#pragma deprecated" should be ported and extended...
Then the driver could produce deprecated warnings for cases like this one or when one uses an old mudlib interface which will be removed from the lib...

**Comment by thefallentree** [comment]
How big is your mudlib code , huh?  I would to fix this, you probably just need a afternoon with some grep .
The driver can not keep old stuff it for ever, especially that we don't currently have a formal release schedule.

**Comment by cartercheng** [comment]
I think it is currently a bit of a problem since for many mudlibs even getting the original authors to sign off on distributing modifications is quite complicated. The thing about this change that is a bit strange is the 'star' form predates the array form so many of the libs in the 90s switched to the array reserved word as a default. In the case of muds that are already running this might not even be possible since the mud admin might not have ownership of all the code in the domains/areas directories.

**Comment by thefallentree** [comment]
this is actually not hard to do, and I frankly think i made the mistake, it should be reverted.

**Comment by cartercheng** [comment]
It would be nice to see it reverted since I think quite a few libs where no one currently active has the right to modify them and distribute them(except maybe Cratylus) depend on it.

**Comment by thefallentree** [comment]
Hi,

Upon closer look, the support for "array" reserved word wasn't really removed at all!, it was just moved from local_options to base/internal/options_internal.h ,

you can still define  ```#define ARRAY_RESERVED_WORD``` in local_options to get it back.

**Comment by keeperofkeysAU** [comment]
Hi

[CC] vm/internal/base/mapping.o
[CC] vm/internal/base/object.o
[CC] vm/internal/base/program.o
[CC] vm/internal/base/svalue.o
[CC] packages/trim/trim.o
[CC] packages/matrix/matrix.o
packages/matrix/matrix.cc:6:25: fatal error: ../base/std.h: No such file 
or directory
compilation terminated.
Makefile:63: recipe for target 'packages/matrix/matrix.o' failed
make: *** [packages/matrix/matrix.o] Error 1

Fixed this by changing line 6: to ../../base/std.h

Next Error:

blackdawn@Dawn:~/fluffos-v3/fluffos/src$ make
[CC] packages/matrix/matrix.o
packages/matrix/matrix.cc:10:25: fatal error: ../lpc_incl.h: No such 
file or directory

Issue is lpc_incl.h is no where to be found?

Regards,
Adam
