### ISSUE TITLE
Promote forum.fluffos.info

### ISSUE THREAD

**Issue by thefallentree** [fluffos/fluffos#351]
Need some work on updating the README.me and current fluffos Webiste. 

We also need to migrate some of the discussions into https://forum.fluffos.info

**Comment by thefallentree** [comment]
Also, not sure if we can import the old LPMuds forum contents to the new forum.

**Comment by cartercheng** [comment]
I think the old content is basically corrupted and Cratylus doesn't have the time to fix it which is why the forum remains down.

**Comment by Shea690901** [comment]
I applied several **months** ago to the old forum, sadly no reaction...
So the assumption about Cratylus´ time sadly seems correct...

**Comment by thefallentree** [comment]
the website is updated with forum link
