### ISSUE TITLE
Valgrind doesn't recognized instructions generated by clang

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#354]
Valgrind doesn't seem to completely recognize the instructions generated by the clang backend. Since Valgrind is currently used to validate pull requests made to the Fluffos project, this is a bit of an issue.

**Comment by thefallentree** [comment]
I think this is not a general issue, it is just the way your code was compiled under LLVM caused the issue.

However, I also discovered valgrind wouldn't work with go code, so it is a bit of issue, we should remove it.

**Comment by thefallentree** [comment]
closed for now
