### ISSUE TITLE
Add unit testing framework to the driver

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#355]
The current testsuite is a nice addition but I suspect it would be even better if we could have a unit testing framework to test modules individually rather than testing the whole system at once after it is compiled.

**Comment by thefallentree** [comment]
yes, maybe we can use https://github.com/google/googlemock ?

We also probably need some refactoring regarding to makefile.

**Comment by cartercheng** [comment]
is googlemock related to the google testing framework?

**Comment by Shea690901** [comment]
According to it´s readme both got merged with https://github.com/google/googletest being the new home for both...

**Comment by cartercheng** [comment]
I read the tutorial but I am unsure about standard practice. Is there a canonical way for running a lot of tests on separate modules? Would we have a separate test main for each .cc file focusing on that module?

**Comment by cartercheng** [comment]
Or do we link everything together before testing with a single main calling all the tests across all modules?

**Comment by thefallentree** [comment]
separate main and separate tests with only minimum file linked are the best.

**Comment by keeperofkeysAU** [comment]
I know this is a crazy and totally out there idea... but rather than
bloating the driver more than you already have... how about focusing on
backwards compatibility with older mudlibs....

No one is going to move if it's going to be a pain in the ass for them to
do so. Which would mean out wasting you time

**Comment by thefallentree** [comment]
These 2 goals are not mutually exclusive .  You can have as many as single file tests you like, and we can still run current testsuite to test driver as a whole.

**Comment by thefallentree** [comment]
BTW, consider using CMAKE / CTEST ,  now we have a libdriver.a  and mainlib.cc generated from Makefile, it will make things much easier to start having separate tests running.

**Comment by thefallentree** [comment]
@Adam

I know there must be frasutration about backwards compatibility, but it is
a team effort. Can you provide some information about what kind of backward
compatibility issue you are facing, it will be great.  In a separate issue
of course.

**Comment by cartercheng** [comment]
I downloaded and installed googletest directly from the repo and installed it. I added some unit testing for the new otable i wrote in the googletest format it seems to work all that is really needed now is to add something to the make file to make the testing more automated (and perhaps some sort of test or instructions for building and installing googletest).

**Comment by cartercheng** [comment]
Sort of added this in the latest pull request now. make googletest runs currently a single test file associated with the otable.cc but this can be extended to cover the entire driver.

**Comment by cartercheng** [comment]
The beginning of this has been added but needs to be elaborated. Only the otable.cc module has some unit tests. It would be nice if we could get to the point of close to 100% coverage based on the unit testing.
