### ISSUE TITLE
Some maintenance for 2.xx branch?

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#360]
I have been toying around with the idea of working on doing some maintenance on the 2.xx branch for people not wanting all the new features that are still sometimes only partially tested in 3.xx. I have managed to get the 2.27 branch with some modifications working under OS X. 

I have in some cases removed some things-

posix timers (since os x doesn't seem support these fully).
malloc variants (i figure nowadays and until a garbage collector is implemented the standard malloc should be good enough).

Added-

conversion to using the clang++ compiler for compilation so that c++ code can be incorporated into the source tree. Some minor modifications with type conversions to make the code compile under c++.

once I do some more maintenance on the code and test it under linux and cygwin I will push it to a github repository as perhaps 2.28. I might migrate some of fallentrees fixes in from the 3.0 branch once i figure out how to incorporate them.

**Comment by cartercheng** [comment]
I just tested this under ubuntu 16.10 and it works .

**Comment by cartercheng** [comment]
I made some additional changes to my copy of fluffos which is on fluffos-2 under my name atm. It now should compile on linux/os x and freebsd.

**Comment by keeperofkeysAU** [comment]
system_libs is made when you run ./build.fluffos for packages that require
external libs

Your package needs a make tidy

**Comment by keeperofkeysAU** [comment]
I have a patch or two of like to submit but I'm not on got so I'll just
reply to this again when I get home

**Comment by cartercheng** [comment]
I fixed this by running make spotless.

**Comment by cartercheng** [comment]
Just go ahead and submit a pull request when you are ready.

**Comment by thefallentree** [comment]
I wasn't planning to maintain 2.xx branch. But now I also don't really have time to maintain 3.x branch. I would welcome some thoughts.

**Comment by cartercheng** [comment]
I think the main problem for the older audience of users which is probably shrinking is that 3.x isn't really backwards compatible and perhaps not entirely tested. I guess for me the problem is that there doesn't seem to be that much of an audience left which is a bit of disincentive for doing much extra development now. There were a couple things I was thinking of attempting- moving the build process to cmake and adding a testing framework. I might just instead work on some of my own projects when I have time.

**Comment by thefallentree** [comment]
after thinking about it, i still consider it is not useful to maintain 2.X branch anymore. I will put in more effort making 3.0 more compatible with old mudlib , ensuring a transition. But I can only do that with help of more crowd testing.
