### ISSUE TITLE
OS X and POSIX timers

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#366]
There is a lingering issue with later versions of the fluffos 2.xx series and OS X. It seems like the #undef support for POSIX timers is no longer complete with some critical stuff deleted. This means the driver will not function on OS X based systems. I patched this in the 2.xx fluffos-2 repo but I am uncertain if a similar patch would work for 3.0.

**Comment by thefallentree** [comment]
what is the error you are getting?

**Comment by thefallentree** [comment]
dup #378
