### ISSUE TITLE
header clash in BSD replace current max macros with numerical_limits<>

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#367]
There is some problem with BSD in how the defines for the max int etc are derived. I remember fixing this too but not entirely sure what I did. I suspect replacing the MAX stuff with numerical_limits<> is better anyhow since it's more C++ style.

**Comment by thefallentree** [comment]
are you talking about BSD or OSX ? eitherway I need a dev environment to test

**Comment by quixadhal** [comment]
For BSD, you could easily setup a virtual machine for testing purposes.  OS X may be more problematic, as Apple likes to try to prevent installation on non-Apple hardware.  You can even download a pre-installed VM image if you’re extra lazy, like me. 😊

https://www.osboxes.org/freebsd/

Sent from Mail for Windows 10

**Comment by thefallentree** [comment]
dup #378
