### ISSUE TITLE
output full debug.log location on error.

### ISSUE THREAD

**Issue by wromfey** [fluffos/fluffos#383]
driver config过程中提示
```
call_out(0) nest level: 1000
==============================
Initializing internal stuff ....
log/debug.log: No such file or directory
Event backend in use: epoll
```
config里设置相应的log目录路径正确 但实际上log目录需要建立在driver文件根目录下才可正常建立debug.log文件
望下一版本修正#00

**Comment by Yeeler** [comment]
我也遇到过这个问题，其实这不算是bug, 你mudlib config文件试着放mudlib根目录了吗？除了最上边的
mudlib绝对路径和bin绝对路径 是系统的/
之后的/ 都是以你mudlib目录 作为根目录

一般来说 mudlib config文件 需要和mudlib一起存放。不同的mudlib 需要不同的配置文件。这样做也便于mudlib的版本控制。

**Comment by thefallentree** [comment]
The log directory in runtime config is an system path ,  it can be a relative path, but relative to the working directory of the driver.
