### ISSUE TITLE
Update EFUN : allocate docs

### ISSUE THREAD

**Issue by zero9k** [fluffos/fluffos#398]
The EFUN allocate should be like this:
varargs mixed allocate( int size, mixed default_value )
So that we can use it as:
1. mixed a = allocate(0);
2. string *b = allocate(20);
3. mixed c = allocate(100, "abc");
4. mixed d = allocate(100, allocate(100, ({ 3, 4, 5 })));
........
:P

**Comment by carl-lucas** [comment]
Allocate actually does work like that already - in fact, you can provide a functional as the second argument, and thus do things like (for example):

`int *rolls = allocate(50, (: 1 + random(100) :));`

 to get 50 random numbers between 1 and 100.

**Comment by zero9k** [comment]
Really? You mean the feature I requested is already there? Then the Efun doc should be updated. I still use simul_efun to do that - -!

**Comment by thefallentree** [comment]
Can someone update the docs? @carl-lucas  or @cartercheng  ?

**Comment by thefallentree** [comment]
Fixed by #399
