### ISSUE TITLE
error: You must have local_options file, see options.h.

### ISSUE THREAD

**Issue by VCF** [fluffos/fluffos#401]
The [build instructions](https://fluffos.github.io/build.html) were non-functional for me. My issue is the same as reported in Issue #320, which was opened and closed, but appears to still be an issue. @ChieveiT suggested that using a different commit might work, I tried that but it didn't resolve the problem:

```
# Just to make git checkout not complain from previous install attempts:
rm src/local_options
git checkout 'fluffos-3.0-alpha8.2'
# build as per instructions:
cd src
cp local_options.testrelease local_options
./build.FluffOS
# Fails with "configure: error: You must have local_options file, see options.h."
```
I'm not sure if I correctly interpreted @ChieveiT's advice, though...
`Ubuntu 14.04.5 LTS`; Also FWIW you may want to include `bison` as one of the required packages in the installation instruction.
Thanks!

**Comment by thefallentree** [comment]
The 8.2 Tag is obsolete , please use the latest release version 3.0.20170907 .

The build instruction obviously need some updating, I will do it soon

**Comment by VCF** [comment]
To clarify, the build failed for both the current version and 8.2 (and both failed with the same "You must have local_options file" message). I attempted 8.2 only because a comment in #320 suggested that using an older build might resolve this particular error.

**Comment by ddawnbb** [comment]
Don't copy, just build with the original local_options file.

**Comment by Aliscad** [comment]
Still got the same error with ubuntu-14.04.5-desktop-amd64 + whatever you have in the github. I am doing it just to try to host a mud game. Please fix it.

**Comment by Shea690901** [comment]
Have you used the shipped ```local_options```? Or have you copied one of the ```local_options.test*```?
In the former case there shouldn't be any problems, in the latter case see comment by @ddawnbb...
Of course, you may change the defines to your like and if you want some explanations what those defines do you may either just take a look into ```local_options.README``` or even use this file as your ```local_options``` file (**that** one works!)...

**Comment by Aliscad** [comment]
No, I just used whatever in the github. I did not edit anything at all.

**Comment by Shea690901** [comment]
Hmmm....
From which directory did you call ```build.FluffOS```?
As way configure currently works, one can't run configure (build.FluffOS) from any directory other than the src directory itself!!!
As such a build directory currently doesn't work!!!

**Comment by Aliscad** [comment]
This is what does local_options looks like

#include "local_options.testdev"

#undef DEBUGMALLOC
#undef DEBUGMALLOC_EXTEBSUIBS
#undef CHECK_MEMORY

I just double-checked the calling path
***@ubuntu:~/fluffos/src$

Then after you ./build.FluffOS you end up with following error
....
checking for working strtod... yes
configure: error: You must have local_options file, see options.h.

Where that 'local_options" as a file does exist in the same folder. But there is no such file called "option.h".

**Comment by Aliscad** [comment]
I believe it would most beneficial that you could just install an ubuntu and follow thru those steps included in the instruction. Thru the steps some of the packages that are required were not mentioned in the instruction. Other than that I did not run into any other problems. It would be great if you could just install it by only following steps, in addition to finding all missing packages that are required and added them to the steps, you could pretty much recreate the error and figure out what is missing there.

**Comment by Shea690901** [comment]
That's not the default ```local_options``` but ```local_optioms.testrelease```...
And yes, in a way it's buggy (since the testdev version is buggy)...

At best use a copy of ```local_options.README```. The default is (not counting a comment at the begining) merely a copy of the readme with it's comments removed....

**Comment by Aliscad** [comment]
Yes, after copying local_options.README, it built successfully. 
Perhaps you should update that local_options. thank you.

**Comment by thefallentree** [comment]
pls reopen if there are issue.
