### ISSUE TITLE
#undef PACKAGE_UIDS  Can cause compile errors

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#403]
vm/internal/master.cc 

: 在函数‘void set_master(object_t*)’中:
vm/internal/master.cc:115 

:5: 错误：‘ret’在此作用域中尚未声明
     ret = apply_master_ob(APPLY_DOMAIN_FILE, 1);
     ^~~
make: *** [Makefile:64：vm/internal/master.o] 错误 1

**Comment by Shea690901** [comment]
Oops...
That´s my mistake :(
Sadly I currently can´t correct it myself :(

Could please somebody with a functioning editor change `vm/internal/master.cc` lines 95-101
from:
``` CC
void set_master(object_t *ob) {
#if defined(PACKAGE_UIDS) || defined(PACKAGE_MUDLIB_STATS)
  int first_load = (!master_ob);
#endif
#ifdef PACKAGE_UIDS
  svalue_t *ret;
#endif
```
to:
``` CC
void set_master(object_t *ob) {
#if defined(PACKAGE_UIDS) || defined(PACKAGE_MUDLIB_STATS)
  int first_load = (!master_ob);
#endif
svalue_t *ret;
```

**Comment by seikichin** [comment]
thanks a lot,let me check it later

**Comment by Shea690901** [comment]
**That** is (in a way) as intendet ;)
The patch that introduced the bug you encountered changed the semantics of the applies `master::author_file()` and `master::domain_file()`.
The messages you´re receiving are telling you, that you´re using the old semantics and as such the driver is using that old semantics as fallback. The new semantics is documented:

Excerpt from doc/applies/master/author\_file.4:
> At startup the driver will ask for the master author by calling author\_file(\_\_MASTER\_FILE\_\_).

Excerpt from doc/applies/master/domain\_file.4:
> At startup the driver will ask for the backbone domain by calling domain\_file("/").

**Comment by seikichin** [comment]
thank you

**Comment by Shea690901** [comment]
Grmbl....
Since when cygwin installer doesn´t need admin rights anymore? Or did I just never notice because normaly I have those?

Regardless... I´m just now installing cygwin (which might take a while cause of my rather slow net connection) and as soon as it´s complete I´ll sumit a PR for this issue....

Question:
Shall I extend the messages, perhaps including a notice to check the manual pages?
