### ISSUE TITLE
in fluffos 3.0 efun opcprof() no longer exist 

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#404]
opcprof() - reports statistics on calling frequencies of various efuns
this efun is no longer exist in fluffos.

**Comment by seikichin** [comment]
能不能提供一个打印当前driver efuns列表的efun，方便新手学习efun

**Comment by cartercheng** [comment]
I really don't know about this. You would have to ask fallentree since I don't know if he stripped out some code. Like most things it's probably not too hard to add back in if that is intended.

**Comment by thefallentree** [comment]
opcprof is mostly useless.  I don't see any need to bring it back. 

an efuns list is easy and I can see its usefulness, I will add one when I have time.

**Comment by thefallentree** [comment]
created #449  to track the request, closing this one.
