### ISSUE TITLE
autotools

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#407]
Why not using libtool and automake too?

At least the usage of automake would make the addition of further / removal of obsolete sources easier...

**Comment by cartercheng** [comment]
Is autotools (which is quite old) better than cmake as a build system? I am not an experienced enough of a C/C++ coder to know if there are other options as well. I think edit source code is a bit complicated so might require a bit of work to emulate in another build system.

**Comment by quixadhal** [comment]
Autotools is the “standard” for GNU’s configure/autoconf system, which makes it pretty decent across most UNIX variants.  It’s a PITA to work with, and very convoluted… but once you get the hang of it, it does make it far simpler for dealing with “Is the library needed?  If so, where is it?” types of issues.  If you were to successfully move the pre-build system to it, you could do the standard “configure && make && make install” style of build.

On the plus side, many of the things that are currently done by build.FluffOS and are defined in local_options would become arguments to configure.  Such as configure –with-math-package –with-matrix-package, etc… At that point, one could easily write a small shell script to let the user pick a few options to run with, or hand-run configure to have full control.

On the minus side, maintainers would need to update the autoconf files so they stayed current, and of course it does nothing for a native Windows build process (Visual Studio).

Sent from Mail for Windows 10

**Comment by Shea690901** [comment]
As I wrote:
The usage of automake would make it easier to add new files to the build process and since I need to add (and remove) some files for my other project (char* -> std:string where ever possible) I´m currently doing an overhaul of configure.ac (every few days in the evening)...
It would be quiet simple to change the local_options file to configure options (shall I?)...

Concerning the overhaul:
I´ve already removed some duplicate lines, reordered others (to put similar tests together) and added a little eye candy (for those who know a little about configure scripts and for the maintainers in case there are problems during configure).
I'm nearly through and will then create a first PR before I start with adding automake...

**Comment by Shea690901** [comment]
Hmm....
According autotools manual is [AC_HEADER_DIRENT](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Particular-Headers.html#index-AC_005fHEADER_005fDIRENT-606) obsolete (there are more)...

Shall I remove those obsolete tests (and possibly breaking the build process on ancient platforms) or shall I keep those tests?

**Comment by cartercheng** [comment]
Shea690901 do you have an email I can reach you at? mine is cartercheng@gmail.com. There are some things I would like to revise in the Fluffos 3.0 code but I would like some input on it but it doesn't quite fit the issue format.

**Comment by cartercheng** [comment]
I think LLVM uses cmake which is why I was wondering since that project could probably have used autotools as well.

**Comment by thefallentree** [comment]
automake is already done.
