### ISSUE TITLE
can't "build.FluffOS develop"

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#409]
Is this a cygwin specific problem or is that wider spread?

I'm using either clang 4.0.1 or (default) gcc 6.0.4.
The offending option is ```-fsanitize=address,undefined```.
clang tells me that this options isn't upported under cygwin while gcc says I'm missing ```libasan.a``` and ```libubsan.a```. Neither is contained in any cygwin package...

**Comment by cartercheng** [comment]
You would have to ask fallentree- I haven't heard from him in a while though.

**Comment by Shea690901** [comment]
According to the webpage, the sanitzer **should** be part of both clang and gcc, meaning I would have to build at least one of them...
And to be honest: I don't want to learn how to build cygwin packages, which would be neccessary since under Windoze it's impossible to change a file (e.g. a library) that is in use by any process, as such I'll sooner exclude those options from CFLAGS when building under cygwin....

**Comment by cartercheng** [comment]
I think it is but I am not sure how that would work if the platform is unsupported perhaps ask on the clang/gcc mailing list?

**Comment by Shea690901** [comment]
Too lazy in this case ;)

I'll just exclude the sanitizer option and keep a lookout should it appear at one point in time...
