### ISSUE TITLE
Missing vm/internal/options.autogen.h file

### ISSUE THREAD

**Issue by MonkeyFreeZone** [fluffos/fluffos#410]
Ubuntu 16.04 x64 new install
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
git - Current (as of today) master of FluffOS
build.FluffOS runs without complaint.

make fails with error
```
[CC] vm/internal/compiler/lex.o
vm/internal/compiler/lex.cc:36:41: fatal error: vm/internal/options.autogen.h: No such file or directory
compilation terminated.
Makefile:63: recipe for target 'vm/internal/compiler/lex.o' failed
make: *** [vm/internal/compiler/lex.o] Error 1
```

I was able to successfully compile on different hardware with Ubuntu 16.04 x64 workstation maybe two weeks ago with the same local_options and installed ubuntu packages.  I'll look to see if the file exists on the workstation when I'm able.

**Comment by Shea690901** [comment]
It should be generated during the build process...
Have you called ```build.FluffOS```?

**Comment by MonkeyFreeZone** [comment]
To your first question, yes, build.FluffOS ran without any major complaints. I'm only seeing 7 "no" answers in the 'checking for .... ' output section. I've saved the output from git clone, git checkout, build.FluffOS, and make if that will help.

Also - thanks for specifying that the file should be generated as part of the build.FluffOS run. I suspected it when looking at the script, but wasn't 100% sure.

**Comment by Shea690901** [comment]
Theoretical the only interessting part would be, if there is any thing different to:
```
[...]
configure: creating ./config.status
config.status: creating Makefile
config.status: creating configure.h
           ------------------------
[CC] tools/build_applies.o
[Linking] tools/build_applies.autogen
[Generating] tools/make_func.autogen.cc
[CC] tools/make_func.autogen.o
[Linking] tools/make_func.autogen
[Generating cc.h]
[Generating Packages]
rm: cannot remove 'packages/packages.autogen.spec': No such file or directory
rm: cannot remove 'packages/packages.autogen.makefile': No such file or directory
rm: cannot remove 'packages/packages.autogen.fullspec': No such file or directory
[Generating applies table...]
[Generating efun tables...]
[Generating grammar...]
[Generating options_def...]
[...]
```

The part above the line stems from the configure run, the part below from the call to ```make help```...

**Comment by MonkeyFreeZone** [comment]
Might be on to something - there's a warning and a complaint about a directory.

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating configure.h
[CC] tools/build_applies.o
[Linking] tools/build_applies.autogen
[Generating] tools/make_func.autogen.cc
[CC] tools/make_func.autogen.o
tools/make_func.y: In function ‘int yylex()’:
tools/make_func.y:372:32: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buff, 2047, yyin);
                                ^
[Linking] tools/make_func.autogen
[Generating cc.h]
[Generating Packages]
rm: cannot remove 'packages/packages.autogen.spec': No such file or directory
rm: cannot remove 'packages/packages.autogen.makefile': No such file or directory
rm: cannot remove 'packages/packages.autogen.fullspec': No such file or directory
[Generating applies table...]
[Generating efun tables...]
[Generating grammar...]
[Generating options_def...]
/usr/bin/env: ‘python’: No such file or directory
***************** Configuration completed **************
```

**Comment by Shea690901** [comment]
The warning concerning ```fgets``` is not neccessaryly a bad thing (although it shows you have more warnings enabled than I)...
The problem is the last one:
```/usr/bin/env: ‘python’: No such file or directory```
It's not a directory, it's a file that's missing: the python interpreter...
Either you have no python installed or it's missing from your PATH, either way you've gor a problem, because without the build will always fail...

Personaly I believe it's the former case, that would be rectified by:
``` sh
sudo apt-get update
sudo apt-get install python
```

(I hope I got the package name for python right ;) )

**Comment by MonkeyFreeZone** [comment]
No worries - I'll figure out the package name, do a make clean, and re-run thebuild.FluffOS.
So it appears we need python for building the driver but not running it. I'll re-post when I have the results - I'm out of town today.

**Comment by MonkeyFreeZone** [comment]
installing python fixed the issue. I was able to make clean, build.fluffos and then make successfully. Thanks for all of the help.

**Comment by quixadhal** [comment]
If python is a required part of the build process, it should probably be checked for in the build.FluffOS script.

Assuming it’s still bash, a simple if [ ! -x /usr/bin/python ]; then ….  fi should do the trick… issuing an error message if it’s not there.  -x is the file exists and has execute permissions set.

Sent from Mail for Windows 10

**Comment by Shea690901** [comment]
Note to self:
Add a check for python to configure.ac ;)
