### ISSUE TITLE
Error compiling fluffos-3 on armbian

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#414]
I tried this and ran into an error with some of the system header files with async.cc. It seems like it cannot find the define for SYS_getdents for the syscall.

**Comment by cartercheng** [comment]
I managed to "fix" this by changing SYS_getdents to SYS_getdents64 which is defined in a header file in /usr/include in armbian. I think from a semantics perspective this is correct but I am unsure of the best way to fix this for the repo. perhaps add an #ifndef SYS_getdents #define SYS_getents SYS_gendents64 #endif?

**Comment by cartercheng** [comment]
Actually this seems a bit wrong I gather getdents and getdents64 don't take the same arguments.  The dirent structure is slightly different according to the man pages.

**Comment by Shea690901** [comment]
What is armbian for a type of system?? Never heard of it...

But considdering getdents/getdents64:
According what I found at man7.org for both sys calls

> These are not the interfaces you are interested in.  Look at
> readdir(3) for the POSIX-conforming C library interface.  This page
> documents the bare kernel system call interfaces.

Any chance to change the code accordingly?

**Comment by cartercheng** [comment]
armbian is a version of debian for ARM cpus but I cannot find an include file describing getdents system call (number of the call).

**Comment by thefallentree** [comment]
Please reopen issue if this is still a issue.
