### ISSUE TITLE
Why does `private nomask int command_hook(string arg)` became `hidden`?

### ISSUE THREAD

**Issue by xiongmao86** [fluffos/fluffos#417]
I am fixing this mudlib xiongmao86/xkx2001-utf8 . And when I `look` I got `apply() with insufficient permission`, the function is `command_hook`, the what is needed is `private`, but what I has is `hidden`. 

I have check the function and it's declared as `private nomask int command_hook(string arg)`. And I am wondering about why the origin private function is changed to hidden?

**Comment by xiongmao86** [comment]
Oh, the link is [mudlib](https://github.com/xiongmao86/xkx2001-utf8), I don't know why the xiongmao86/xkx2001-utf8 is not showing.

**Comment by xiongmao86** [comment]
If I am supposed to change that, or what should I change it into? `private ini command_hook` or `nomask int command_hook` or anything?

**Comment by xiongmao86** [comment]
Are there any lpc manuals to read? I found nothing on search engine.

**Comment by quixadhal** [comment]
There are these old LPC books that Drakkos wrote a while back,

http://discworld.starturtle.net/external/lpc_for_dummies/lpc1.pdf
http://discworld.starturtle.net/external/lpc_for_dummies/lpc2.pdf

They are quite good, even though they are for an older version of FluffOS and a very old version of the Discworld mudlib.

If I remember right, “private” means you are restricting the function to only being callable by the object in which it’s defined, or perhaps from anything which inherits it.  It would thus be “hidden” from call_out() or call_other().

Sent from Mail for Windows 10

**Comment by xiongmao86** [comment]
Thank you for your kindly reply, @quixadhal , I downloaded the book, and will read it up. At the same time, there is a question I want to ask: it looks like there are some private won’t become hidden, is that right?

**Comment by cartercheng** [comment]
nomask IIRC (been a while) means that you cannot replace the function with something of the same name.

**Comment by xiongmao86** [comment]
Thank you @cartercheng, so I should probably remove `private`.

**Comment by xiongmao86** [comment]
Thank you @cartercheng, you help me a lot.
