### ISSUE TITLE
make: *** No rule to make target `help'.  Stop.

### ISSUE THREAD

**Issue by oiuv** [fluffos/fluffos#419]
run './build.Fluffos' on my mac
.
.
.
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make: *** No rule to make target `help'.  Stop.

**Comment by thefallentree** [comment]
This is actually not an issue,  you can continue just running make and it will build the driver just fine. 

I will fix this later.

**Comment by oiuv** [comment]
How can i fix this error:
.
.
.
otable_test.cc:5:10: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:597: recipe for target 'otable_test.lo' failed
make[7]: *** [otable_test.lo] Error 1
make[7]: Leaving directory '/home/vagrant/fluffos/src/vm/internal'
Makefile:640: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory '/home/vagrant/fluffos/src/vm/internal'
Makefile:518: recipe for target 'all' failed
make[5]: *** [all] Error 2
make[5]: Leaving directory '/home/vagrant/fluffos/src/vm/internal'
Makefile:591: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/vagrant/fluffos/src/vm'
Makefile:647: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/vagrant/fluffos/src'
Makefile:491: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/vagrant/fluffos/src'
Makefile:612: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/fluffos'
Makefile:492: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jpeckham** [comment]
It does cause a non zero return on build.FluffOS which is minor, able to be worked around, but did break my docker build initially.

**Comment by MonkeyFreeZone** [comment]
```
otable_test.cc:5:10: fatal error: gtest/gtest.h: No such file or directory
#include <gtest/gtest.h>
```

I've run up against this same issue recently on the make step.
build.FluffOS doesn't complain about anything.
find /home/username/fluffos -name gtest
returns no results
git clone and git checkout master commands both run today.

Prior to getting to this point, there were some missing package dependencies on my system - build.FluffOS complained about some of them, some of them showed up in the make step, but a little research led to the correct requirements. The orignal Ubuntu install was as a generic workstation. The packages I needed to get the build script and make to quit complaining included:

- bison
- automake
- libtool
- libgtest-dev

Installing the last one (libgtest-dev) got me past the 'missing gtest/gtest.h' compile error.
I hope it does the same for others.  I've got a new compile issue, but it is likely a similar problem: some missing package on my system :)

My system:
Description:	Ubuntu 18.04.1 LTS
Release:	18.04

**Comment by oiuv** [comment]
> ```
> otable_test.cc:5:10: fatal error: gtest/gtest.h: No such file or directory
> #include <gtest/gtest.h>
> ```
> 
> I've run up against this same issue recently on the make step.
> build.FluffOS doesn't complain about anything.
> find /home/username/fluffos -name gtest
> returns no results
> git clone and git checkout master commands both run today.
> 
> Prior to getting to this point, there were some missing package dependencies on my system - build.FluffOS complained about some of them, some of them showed up in the make step, but a little research led to the correct requirements. The orignal Ubuntu install was as a generic workstation. The packages I needed to get the build script and make to quit complaining included:
> 
>     * bison
> 
>     * automake
> 
>     * libtool
> 
>     * libgtest-dev
> 
> 
> Installing the last one (libgtest-dev) got me past the 'missing gtest/gtest.h' compile error.
> I hope it does the same for others. I've got a new compile issue, but it is likely a similar problem: some missing package on my system :)
> 
> My system:
> Description: Ubuntu 18.04.1 LTS
> Release: 18.04

try to make with Commits 65e03b2015219cd70ca5cd8991aa7adc18ed47f2 (on Nov 23, 2017 ),It should work fine on ubuntu.

**Comment by thefallentree** [comment]
master branch is currently in transiting to CMAKE , so things is a little bit funky right now.

Until that is done, i will maintain v2017 release which use the old build system that works great.
