### ISSUE TITLE
Poor perfomance on newer machine

### ISSUE THREAD

**Issue by ecam85** [fluffos/fluffos#420]
We just moved our mud to a newer machine, and the perfomance is poorer than before.
The problem seems to be when reading and loading files. Just to give you an example, speed.c in the testsuite takes about 2s to load in our old machine, but over 4s in the new one.

The new machine should be better in all aspects, but we are wondering if the SSD could be causing problems instead of being faster.

Do you have any experience on running fluffos on a machine with a SSD?

**Comment by thefallentree** [comment]
which version and platform do you use? do you have detailed benchmark?

Fluffos doesn't use any special ops for reading/writing files, just standard library. if it is slow then it will be the reason o the whole system

**Comment by ecam85** [comment]
Thank you for the quick answer. It turns out it was our fault, a change in our mudlib that we did just before moving to the new server, and a series of misleading tests! 
Sorry for the incovenience!
