### ISSUE TITLE
otable_test.cc:5:25: 致命错误：gtest/gtest.h

### ISSUE THREAD

**Issue by heathzhang35** [fluffos/fluffos#425]
otable_test.cc:5:25: 致命错误：gtest/gtest.h：没有那个文件或目录
 #include <gtest/gtest.h>
                         ^
编译中断。
make[7]: *** [otable_test.lo] 错误 1
make[7]: *** 正在等待未完成的任务....
make[7]: 离开目录“/home/mud/fluffos/src/vm/internal”
make[6]: *** [all-recursive] 错误 1
make[6]: 离开目录“/home/mud/fluffos/src/vm/internal”
make[5]: *** [all] 错误 2
make[5]: 离开目录“/home/mud/fluffos/src/vm/internal”
make[4]: *** [all-recursive] 错误 1
make[4]: 离开目录“/home/mud/fluffos/src/vm”
make[3]: *** [all-recursive] 错误 1
make[3]: 离开目录“/home/mud/fluffos/src”
make[2]: *** [all] 错误 2
make[2]: 离开目录“/home/mud/fluffos/src”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/home/mud/fluffos”
make: *** [all] 错误 2

**Comment by heathzhang35** [comment]
make: *** 没有规则可以创建目标“help”

**Comment by daimon99** [comment]
``bash
$ cd src/vm/internal
$ vi
<find otable_test.lo, and delete it>
...
am_libvm_internal_la_OBJECTS = apply.lo eval_limit.lo master.lo \
        otable.lo simul_efun.lo simulate.lo trace.lo \
        vm.lo
...

**Comment by LewisLKP** [comment]
You may refer to https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/ 
and install libgtest package

**Comment by heathzhang35** [comment]
> You may refer to https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/
> and install libgtest package

thanks.
After trying to install gtest 1.8, it still doesn't work. I recompiled it with an older version of fluffos.

[root@localhost make]# ./sample1_unittest
Running main() from ../src/gtest_main.cc
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from FactorialTest
[ RUN      ] FactorialTest.Negative
[       OK ] FactorialTest.Negative (0 ms)
[ RUN      ] FactorialTest.Zero
[       OK ] FactorialTest.Zero (0 ms)
[ RUN      ] FactorialTest.Positive
[       OK ] FactorialTest.Positive (0 ms)
[----------] 3 tests from FactorialTest (0 ms total)

[----------] 3 tests from IsPrimeTest
[ RUN      ] IsPrimeTest.Negative
[       OK ] IsPrimeTest.Negative (0 ms)
[ RUN      ] IsPrimeTest.Trivial
[       OK ] IsPrimeTest.Trivial (0 ms)
[ RUN      ] IsPrimeTest.Positive
[       OK ] IsPrimeTest.Positive (0 ms)
[----------] 3 tests from IsPrimeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (1 ms total)
[  PASSED  ] 6 tests.
[root@localhost make]#

**Comment by heathzhang35** [comment]
> ```shell
> $ cd src/vm/internal
> $ vi
> <find otable_test.lo, and delete it>
> ...
> am_libvm_internal_la_OBJECTS = apply.lo eval_limit.lo master.lo \
>         otable.lo simul_efun.lo simulate.lo trace.lo \
>         vm.lo
> ...
> ```

Although the problem has not been solved, thank you all the same

**Comment by thefallentree** [comment]
You need to install libgtest-dev

**Comment by heathzhang35** [comment]
> You need to install libgtest-dev

I have installed the old version of fluffos and solved it temporarily. Thank you.

**Comment by heathzhang35** [comment]
> $ cd src/vm/internal $ vi <find otable_test.lo, and delete it> ... am_libvm_internal_la_OBJECTS = apply.lo eval_limit.lo master.lo \ otable.lo simul_efun.lo simulate.lo trace.lo \ vm.lo ...

Thank you for your help.

**Comment by heathzhang35** [comment]
I seem to have seen that gtest has been removed from the latest fluffos source code?
