### ISSUE TITLE
/cmake目录中缺少FindOPENSSL.cmake文件一枚

### ISSUE THREAD

**Issue by sayeah** [fluffos/fluffos#438]
/cmake目录中缺少FindOPENSSL.cmake文件一枚
导致开启编译cyrpto出错

**Comment by thefallentree** [comment]
what version of cmake are you using?

**Comment by thefallentree** [comment]
FindOPENSSL is included by default by cmake, so this must be a local issue.

**Comment by thefallentree** [comment]
actually this is caused by misspelling. fix are coming in.
