### ISSUE TITLE
Crash when using oldcrypt

### ISSUE THREAD

**Issue by justinm** [fluffos/fluffos#455]
oldcrypt() may crash FluffOS v2017.2018120702 when the first two characters of a salt contains certain characters, particularly a $. According to the documentation for crypt, $ is used as a special code for instructing crypt to use different encryption algorithms.

Steps to reproduce: `oldcrypt("213sadf", "$1$df");`

At one point during my muds existance, player passwords were being encrypted with the "$1$" format, but I have yet to determine how. crypt() does not seem to produce this format.

**Comment by Shea690901** [comment]
Have you switched to MacOS?
According [Wikipedia](https://en.wikipedia.org/wiki/Crypt_(C)#Support_in_operating_systems) MacOS doesn't support MD5 hashes...

**Comment by justinm** [comment]
This issue is reproducible on Ubuntu via Docker.

**Comment by thefallentree** [comment]
@justinm yeah, I know what this is now,  that is the MD5 format and will be fixed
