### ISSUE TITLE
MIN_INT is not -9223372036854775808,but -9223372036854775807

### ISSUE THREAD

**Issue by oiuv** [fluffos/fluffos#457]
```c
int main(object me, string arg)
{
    int a = MAX_INT, b = MIN_INT, c = b - 1;
    printf("a = %d\nb = %d\nc = %d\n", a, b, c);
    return 1;
}
```
when I test this, the result is：
> a = 9223372036854775807
> b = -9223372036854775807
> c = -9223372036854775808

MIN_INT should be -9223372036854775808，but output -9223372036854775807。

----
why #define MIN_FLOAT 0.000000 ? bug?

**Comment by thefallentree** [comment]
see https://github.com/fluffos/fluffos/blob/2c5a5af93c1a507e217ad77b716f814233caed21/testsuite/single/tests/compiler/64bit.c#L95
