### ISSUE TITLE
一定要cmake 3.10？arm64可以支持么？

### ISSUE THREAD

**Issue by zixijian** [fluffos/fluffos#460]
我在安卓手机chroot环境中编译，debian9默认的cmake3.72 项目无法生成，如果仅仅是cmake版本的问题，我得自己手动编译新版cmake了。

**Comment by zixijian** [comment]
我下载编译了最新的cmake 3.14.5，再生成还是不行。

-- PACKAGE: uids ON
-- ALL PACKAGES: package_compress;package_contrib;package_core;package_crypto;package_db;package_develop;package_math;package_matrix;package_mudlib_stats;package_ops;package_parser;package_pcre;package_sha1;package_sockets;package_trim;package_uids
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Libevent: Found unsuitable version "", but required is at
  least "2.0" (found /usr/lib/aarch64-linux-gnu/libevent.so)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibevent.cmake:82 (find_package_handle_standard_args)
  src/CMakeLists.txt:213 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by thefallentree** [comment]
This is because you don't have libevent2 installed

**Comment by zixijian** [comment]
libevent2 跟libevent-2.0-5不一样么？
Note4x:~# apt show libevent-2.0-5
Package: libevent-2.0-5
Version: 2.0.21-stable-3
Priority: standard
Section: libs
Source: libevent
Maintainer: Anibal Monsalve Salazar <anibal@debian.org>
Installed-Size: 316 kB
Depends: libc6 (>= 2.17)
Homepage: http://libevent.org/
Tag: role::shared-lib
Download-Size: 129 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.tuna.tsinghua.edu.cn/debian stretch/main arm64 PackagesDescription: Asynchronous event notification library
 Libevent is an asynchronous event notification library that provides a
 mechanism to execute a callback function when a specific event occurs
 on a file descriptor or after a timeout has been reached.
 .
 It is meant to replace the asynchronous event loop found in
 event driven network servers. Currently, libevent supports /dev/poll,
 kqueue(2), event ports, select(2), poll(2) and epoll(4).
 .
 For backward compatibility and to transition to "libevent_core only"
 or "libevent_core + libevent_extra", the libevent source package builds
 the libevent library that includes everything in libevent_core and
 libevent_extra.

**Comment by zixijian** [comment]
删掉FindLibevent.cmake检测内容项目可以正常生成，但是gcc版本又太高了，debian9自带6.3，而且是arm64，只能自己编译编译器了。
