### ISSUE TITLE
question concerning src/fliconv.cc

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#466]
Why is there a distinction between Linux on one side and all other OS on the other???

```
get_translator(...) {
...
#ifdef __linux__
  strcat(name, "//TRANSLIT//IGNORE");
#endif 
...
}
```

**Comment by thefallentree** [comment]
I have no idea. I am actually going to abandon the iconv library in favor of using ICU directly.  which should much simpler to use.

**Comment by thefallentree** [comment]
this file is gone now
