### ISSUE TITLE
v2019 builds on macOS Mojave 10.14.6 natively

### ISSUE THREAD

**Issue by z3ndrag0n** [fluffos/fluffos#473]
Benefit of building natively (I assume): JEMALLOC definitely works (at least with the patch I sent for name mangling);

Compiled with:
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

successfully ran lil tests (well by successfully I mean up until it ran crasher...)

Dead Souls is bitching about line 128 in /secure/sefun/sefun.h, so will try some other mudlibs and see what I can see

**Comment by thefallentree** [comment]
Great news! If you can update what you use to installed all the library that would be great. 

This issue can be closed in reference to #472  #471

**Comment by z3ndrag0n** [comment]
Quick update: (sorry I know it's not kosher on a closed issue, but you did ask!)
- I have final_realms_fluffos_v1 up and running with basically only the following changes required:
   1. #define status int (in every lpc file where status is used, could also find and replace);
   2. remove the static qualifier from every plc file where it (still) appears.
These were the only issues so far - I'll do the same to all the other mudlibs that had an _fluffos_v1 port available, starting with dead souls;
Regarding the libraries, pretty much for each library:
./configure && make && make check && sudo make install
(happy to build up an mpkg of the required libraries if we think this will help people)

Cheers and hope this helps,
Barry (aka Draconis on a couple of LPmuds about 30 years ago!)
