### ISSUE TITLE
FindMySQL.cmake produces src/CMakeFiles/driver.dir/link.txt which doesn't work on (at least) macOS

### ISSUE THREAD

**Issue by z3ndrag0n** [fluffos/fluffos#483]
Sorry - I forgot this last time as of course this all gets generated under build and so is ignored by git diff.

link.txt required hand-editing to replace -lmysqlclient -lssl -lcrypto with /usr/local/mysql/lib/libmysqlclient.dylib /usr/local/mysql/lib/libssl.dylib /usr/local/mysql/lib/libcrypto.dylib

I'll get around to working out what the appropriate CMake incantations in the next couple of days unless someone beats me to it.

Cheers,
Barry

**Comment by thefallentree** [comment]
fixed in #489 

checkout .github/workflow/ci-osx.yml for setting up environments.
in general, just brew install mysql and everything would work.
