### ISSUE TITLE
Release v2017.2019102201在cyg环境下不生成 driver.exe

### ISSUE THREAD

**Issue by suimengjushi** [fluffos/fluffos#487]
[CC] comm.o
comm.cc:65:6: 警告：‘void {anonymous}::maybe_schedule_user_command(interactive_t*)’ defined but not used [-Wunused-function]
 void maybe_schedule_user_command(interactive_t *user) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[CC] fliconv.o
[CC] mainlib.o
[CC] user.o
[CC] net/telnet.o
[CC] thirdparty/libtelnet/libtelnet.o
thirdparty/libtelnet/libtelnet.c: 在函数‘int _environ_telnet(telnet_t*, unsigned char, char*, size_t)’中:
thirdparty/libtelnet/libtelnet.c:598:25: 警告：ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   values[index].value = "";
                         ^~
[Generating libdriver.a]
[CC] main.o
[Linking driver.exe]
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: libdriver.a(scratchpad.o): bad string table size 0
libdriver.a: 无法添加符号: 错误的值
collect2: 错误：ld 返回 1
make: *** [Makefile:198：driver.exe] 错误 1

**Comment by thefallentree** [comment]
I think you may need to clean cache or upgrade cygwin first. It's not related to the current change.
