### ISSUE TITLE
rust build fails on macOS

### ISSUE THREAD

**Issue by z3ndrag0n** [fluffos/fluffos#488]
I'll investigate but not seeing the win here - what was the rationale behind entangling rust with your mud driver?

Compiling percent-encoding v2.1.0
     Running `CARGO_PKG_VERSION_PRE= CARGO_PKG_VERSION_MAJOR=2 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_NAME=percent-encoding CARGO=/Users/bwa/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo CARGO_MANIFEST_DIR=/Users/bwa/.cargo/registry/src/github.com-1ecc6299db9ec823/percent-encoding-2.1.0 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION=2.1.0 CARGO_PKG_AUTHORS='The rust-url developers' CARGO_PKG_REPOSITORY='https://github.com/servo/rust-url/' CARGO_PKG_DESCRIPTION='Percent encoding and decoding' CARGO_PKG_HOMEPAGE= DYLD_FALLBACK_LIBRARY_PATH='/Users/bwa/src/fluffos/target/debug/deps:/Users/bwa/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/bwa/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/bwa/lib:/usr/local/lib:/usr/lib' rustc --crate-name percent_encoding /Users/bwa/.cargo/registry/src/github.com-1ecc6299db9ec823/percent-encoding-2.1.0/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=02fc1e2835fdfad6 -C extra-filename=-02fc1e2835fdfad6 --out-dir /Users/bwa/src/fluffos/target/debug/deps -L dependency=/Users/bwa/src/fluffos/target/debug/deps --cap-lints warn -C link-arg=-Wl,-z,origin -C 'link-arg=-Wl,-rpath=$ORIGIN'`
error: linking with `cc` failed: exit code: 1
...
  = note: ld: unknown option: -z
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by thefallentree** [comment]
fixed in #489 

checkout .github/workflow/ci-osx.yml for setting up environments.
