### ISSUE TITLE
关于 Could not find "mysql.h"  的BUG

### ISSUE THREAD

**Issue by oiuv** [fluffos/fluffos#493]
在某些系统环境下，MYSQL_INCLUDE_DIR 包括多个目录，编译时会报错。

如我在 cygwin 下报错如下：

    CMake Error at cmake/FindMySQL.cmake:512 (message):
      Could not find "mysql.h" in "/usr/include/mysql;/usr/include/mysql/mysql"
      found from running "/usr/bin/mysql_config"

在树莓派中编译报错如下：

    Could not find "mysql.h" in
    "/usr/include/mariadb;/usr/include/mariadb/mysql" found from running
    "/usr/bin/mysql_config"
    Call Stack (most recent call first):
    src/packages/db/CMakeLists.txt:15 (find_package)

我的解决方案是在 FindMySQL.cmake 代码 `if (NOT EXISTS "${MYSQL_INCLUDE_DIR}/mysql.h")` 前（大概510 行位置）加入以下代码：

    # In case mysql_config returns several paths: mysql.h in first
    LIST(LENGTH MYSQL_INCLUDE_DIR n)
    IF( ${n} GREATER 1)
        LIST(GET MYSQL_INCLUDE_DIR 0 MYSQL_INCLUDE_DIR)
    ENDIF()

**Comment by thefallentree** [comment]
fixed in #494
