### ISSUE TITLE
questions to cargo build

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#500]
How does one reconfigure cmake in this environemt (```ccmake .``` says we have no cache)?
How does one build outside the source tree (even when calling ```cargo build --manufest-path ../fluffos``` cwd is empty and the build happened inside ```../fluffos```)?

**Comment by thefallentree** [comment]
Just do cargo clean is sufficient

**Comment by Shea690901** [comment]
and the reconfiguring?
I need a debug build instead of release and I also need to be able to (un)set other cmake vars...

**Comment by thefallentree** [comment]
By default it does debug build, unless cargo was also build in release
mode.

You can still do out of tree cmake,  you can copy what ever you produce
libdriver.so with cargo build Produced fluffos to test .
