### ISSUE TITLE
stdout vs. stderr

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#501]
Why is the output from processing the config file on stdout while the predefines go to stderr???
Wouldn't it be better if either both go to stderr?
Perhaps even with a commandline option telling the driver to (not) print one or both of them?

**Comment by thefallentree** [comment]
@Shea690901 Don't really have an strong opinion about it, I think it can all goto stdout, feel free to send in patches for that.

**Comment by thefallentree** [comment]
I looked the code, most of the stuff were printed with debug_message() , which goes to debug.log as well as stderr . So we are good for now.
