### ISSUE TITLE
Feature request: efun:query_ip_number get the user's real ip address when telnet behind a proxy server

### ISSUE THREAD

**Issue by lostsnow** [fluffos/fluffos#505]
I wrote a websocket proxy to connect telnet, Then I have no way to get the user's real ip address by efun query_ip_number.

Tcp protocol does not have an X-REAL-IP header like HTTP, So is there any way to solve this problem?

**Comment by Shea690901** [comment]
What would you need that IP for? If it where possible to do so, as you wrote: the tcp protocol doesn't have such a header, as such the information is lost once past the proxy.
Anyway you most likely would get something like 10.x.x.x or 192.168.x.x and then multiple occurences of that. Then you have two (or more) people connected from 192.168.0.2 and both of them are using their own computer with thausends of km between them... Not very useful ;)

**Comment by quixadhal** [comment]
I think he means a proxy on the web server that lets you play (use telnet) through a web application?

Many people still do bans or try to verify multi-playing by checking the IP the connection(s) are coming from, and if it’s a web proxy, everyone using it will look like they’re connecting from the web server, not their actual address.

I remember Cratylus had a workaround with Dead Souls a while ago in that it used a modified telnet proxy that passed the actual connection IP address along as an extra argument to the MUD, but obviously the mud has to expect that to make use of it.  I don’t remember the details, but it probably ran on an alternate port that expected the extra parameter… or maybe it passed it along in some other way.

Sent from Mail for Windows 10

**Comment by lostsnow** [comment]
Yes, there is a proxy on the web server and I can not ban or verify user's IP

Demo: https://mud.litsea.com (chinese language)

**Comment by thefallentree** [comment]
This is not possible to do, and it is why we will implement a built in websocket server in v2019.

**Comment by quixadhal** [comment]
My suggestion is to implement an sefun in the mudlib and store a secondary IP address that you negotiate in the connection object.  If undefinedp() is true (no negotiation), return the efun’s results.  But you could then use any system you want to negotiate getting their real address from the web proxy, including TELNET opts if you really want.  You will have to have the source to the web proxy so you can make it do this, obviously.

I vaguely remember using anyterm  https://github.com/quixadhal/bloodlines/tree/bloodlines/public_html/anyterm

But I can’t find the hooks in the dead souls mudlib that made use of it.

Sent from Mail for Windows 10
