### ISSUE TITLE
v2019-mingw64-jemalloc crash

### ISSUE THREAD

**Issue by suimengjushi** [fluffos/fluffos#532]
[Thread 259332.0x35f80 exited with code 0]
[Thread 259332.0x3d2b8 exited with code 0]
[Thread 259332.0x35e10 exited with code 0]
warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffa319791f3 in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffa319791f3 in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffa31981622 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffa3198192a in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffa3198a8e9 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffa318c088d in ntdll!RtlGetCurrentServiceSessionId ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007ffa318bfc11 in ntdll!RtlFreeHeap ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x00007ffa2ffe9cfc in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#7  0x000000006fd1bc1a in ?? () from G:\msys64\home\li\ydzs\libstdc++-6.dll
#8  0x000000006fd1b9ee in ?? () from G:\msys64\home\li\ydzs\libstdc++-6.dll
#9  0x000000006fd369dc in ?? () from G:\msys64\home\li\ydzs\libstdc++-6.dll
#10 0x000000000044ccb6 in read_file ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/basic_string.h:6458
#11 0x00000000004527ae in f_read_file ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/efuns_main.cc:1805
#12 f_read_file ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/efuns_main.cc:1787
#13 0x00000000004abf0a in eval_instruction ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/interpret.cc:3631
#14 0x00000000004bcc65 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:281
#15 0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#16 0x00000000004bdbb3 in safe_apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:347
#17 0x0000000000465da2 in call_out ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/call_out.cc:248
#18 0x00000000004bec17 in on_game_tick ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:690
#19 0x0000000067ed600e in libevent-2-1-7!event_add_nolock_ ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#20 0x0000000067ed69b9 in libevent-2-1-7!event_base_loop ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#21 0x00000000004dd09b in main ()
    at G:/msys64/home/li/fluffos-master/src/backend.cc:226
(gdb)

**Comment by suimengjushi** [comment]
[Thread 266620.0x41184 exited with code 0]
[Thread 266620.0x41188 exited with code 0]
[Thread 266620.0x4118c exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006cd68c36 in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
(gdb) bt
#0  0x000000006cd68c36 in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#1  0x000000006cd6a3e3 in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#2  0x000000006cd05260 in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#3  0x000000006cd6d9ce in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#4  0x00000000004b3f5e in fill_lookup_table_recurse ()
    at G:/msys64/mingw64/include/c++/9.2.0/ext/new_allocator.h:114
#5  0x00000000004bce01 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/apply_cache.cc:59
#6  0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#7  0x000000000049b8e6 in call_create ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/object.cc:1941
#8  call_create ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/object.cc:1930
#9  0x0000000000481d5e in load_object ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/simulate.cc:559
#10 0x000000000047825d in find_object ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/simulate.cc:1460
#11 0x00000000004583b5 in f_find_object ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/efuns_main.cc:663
#12 0x00000000004abe99 in eval_instruction ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/interpret.cc:3638
#13 0x00000000004bcc65 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:281
#14 0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#15 0x000000000049b8e6 in call_create ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/object.cc:1941
#16 call_create ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/object.cc:1930
#17 0x0000000000481d5e in load_object ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/simulate.cc:559
#18 0x000000000047825d in find_object ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/simulate.cc:1460
#19 0x000000000045be3f in f__call_other ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/efuns_main.cc:220
#20 0x00000000004abd68 in eval_instruction ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/interpret.cc:3657
#21 0x00000000004bcc65 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:281
#22 0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#23 0x00000000004bdbb3 in safe_apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:347
#24 0x0000000000465da2 in call_out ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/call_out.cc:248
#25 0x00000000004bec17 in on_game_tick ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:690
#26 0x0000000067ed600e in libevent-2-1-7!event_add_nolock_ ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#27 0x0000000067ed69b9 in libevent-2-1-7!event_base_loop ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#28 0x00000000004dd09b in main ()
    at G:/msys64/home/li/fluffos-master/src/backend.cc:226

**Comment by suimengjushi** [comment]
[Thread 259164.0x40ed4 exited with code 0]
[Thread 259164.0x40dd8 exited with code 0]
[Thread 259164.0x3f95c exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006cd698de in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
(gdb) bt
#0  0x000000006cd698de in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#1  0x000000006cd09070 in ?? () from G:\msys64\home\li\ydzs\libjemalloc.dll
#2  0x000000000049dc9f in restore_object_from_buff ()
    at G:/msys64/mingw64/include/c++/9.2.0/ext/new_allocator.h:128
#3  0x000000000049ec7d in restore_object ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/object.cc:1756
#4  0x000000000043c05a in f_restore_object ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/save.cc:81
#5  0x00000000004abf0a in eval_instruction ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/interpret.cc:3631
#6  0x00000000004bcc65 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:281
#7  0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#8  0x000000000045bf35 in f__call_other ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/efuns_main.cc:231
#9  0x00000000004abd68 in eval_instruction ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/base/interpret.cc:3657
#10 0x00000000004bcc65 in apply_low ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:281
#11 0x00000000004bd2ce in apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:318
#12 0x00000000004bdbb3 in safe_apply ()
    at G:/msys64/home/li/fluffos-master/src/vm/internal/apply.cc:347
#13 0x0000000000465da2 in call_out ()
    at G:/msys64/home/li/fluffos-master/src/packages/core/call_out.cc:248
#14 0x00000000004bec17 in on_game_tick ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:690
#15 0x0000000067ed600e in libevent-2-1-7!event_add_nolock_ ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#16 0x0000000067ed69b9 in libevent-2-1-7!event_base_loop ()
   from G:\msys64\home\li\ydzs\libevent-2-1-7.dll
#17 0x00000000004dd09b in main ()
    at G:/msys64/home/li/fluffos-master/src/backend.cc:226

**Comment by thefallentree** [comment]
This may be related to #535

**Comment by thefallentree** [comment]
This was caused by some bug in the code, and has since been fixed.
