### ISSUE TITLE
Feature request: add modifier support to pcre efuns

### ISSUE THREAD

**Issue by lostsnow** [fluffos/fluffos#543]
Currently `pcre_compile` second parameter is hardcoded:

https://github.com/fluffos/fluffos/blob/280e5b1e6be5a5467b2115da7561d1219036834d/src/packages/pcre/pcre.cc#L339-L343

This parameter is used as a modifier of the regular expression, like `u`, `i`, `m` etc.

An example is to determine if a string is Chinese(utf8):

`"/[\\x{4e00}-\\x{9fa5}]+/u"` or `"/\\p{Han}+/u"`

`u` means `PCRE_UTF8`

**Comment by thefallentree** [comment]
PCRE_UTF8 support has been added, it maybe desirable to add other parameter support, but that's an TODO in the future

**Comment by thefallentree** [comment]
we have pcre_match_all now,  the only common modifier missing is "multiline"
