### ISSUE TITLE
General efun Documentation

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#548]
*grumbl*

Could please someone take a closer look at the efun documentation?
I just found an undocumented feature with ```efun::ctime```...
According documentation that efun takes a ```time_t``` as argument, according code it can also be called as ```efun::ctime(void)``` in which case it will call ```get_current_time()``` to get the ```time_t``` value to convert...

**Comment by thefallentree** [comment]
well, if you find anything incorrect on https://www.fluffos.info/efun/ , just click "edit efun" to change it.

**Comment by thefallentree** [comment]
and I've fixed this one with a couple clicks.

https://github.com/fluffos/fluffos/blob/master/docs/efun/system/ctime.md
