### ISSUE TITLE
testsuite efun::read_file fails

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#552]
Tested for current master branch and for commit 280e5b1e...
Error happens in line 17...

**Comment by thefallentree** [comment]
what platform are you on? There is a couple git attributes change that may require an re-checkout, so pls do an full git clone and retry .

**Comment by thefallentree** [comment]
please reopen if you can reproduce. So far all the CI are fine.

**Comment by thefallentree** [comment]
I found out this happens when you modify master file. I changed in #554 to use dedicated test files now. So this is fixed now.
