### ISSUE TITLE
Build guide for nightmare 3 and 4

### ISSUE THREAD

**Issue by evilmog** [fluffos/fluffos#553]
Hi There,

A number of mudlibs have been posted on lpmuds.net and they don't seem to compile on modern linux, I believe they are targetted at an older version of linux.

coremud.org 4000 is nightmare derived, is it possible to guild a build guide to get nightmare 3 or 4 to work? I think colony is NM4 derived but I can't confirm, the mud admin is busy until Feb 2020 or so but I wanted to give him an upgrade path that's ready to go.

I also experiment with older libs, and intend to make a CTF mud thats NM3 and NM4 based (2 separate muds)

http://lpmuds.net/downloads.html has all the pre integrated libs from a while back

specifically http://lpmuds.net/files/nightmare3_fluffos_v2.zip for nightmare 3 and http://lpmuds.net/files/nightmare4_fluffos_v1.zip for nightmare 4.

would it be possible to write up a guide for getting both of those libs to work with the latest fluffos?

**Comment by thefallentree** [comment]
That is the plan for 2020, after the current websocket work is finished, I plan to start publishing libs that fully works with v2019. 

In the mean time, we can get started by creating some github project to host these libraries and try them with latest fluffos, if you meet any issues let me know.

**Comment by Shea690901** [comment]
What do you mean by 'the mudlib doesn't compile under modern linux'????
1. how do you try to 'compile' the mudlib? Afaik only the DGD driver is able to truly compile a mudlib...
1. what has the linux version (distro) todo with the mudlib/driver pair you're using?
    As long as you can compile the driver that is ;)
    Otherwise you should considder using either a newer driver or an older C-compiler...

The only problem that I would see, is that current drivers (completely independent from the underlying OS!!!) are more strict about the used LPC-types and that they might miss one or another efun, while still other efuns might have changed their signature, both would result in 'compile errors' (from the running driver) when loading an object (or worse in either master.c or simul_efun.c preventing the startup of the mud)...
