### ISSUE TITLE
Bug in efun::mudstatus

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#556]
More precisely with otable status as part of the mudstatus:

After the ```string_stream``` containing the status message is build, it is converted into a ```string```, sadly this conversion takes only the first word from the ```string_stream```.
The test of that efun can only check if the efun returns the correct type (string), not if the actual output is correct (that varies). To be detected is the effect only by visual inspection.

**Comment by thefallentree** [comment]
fixed in #557
