### ISSUE TITLE
json.c解析空字符串会报错，用的2017的版本，不知道有没有关系

### ISSUE THREAD

**Issue by lonag** [fluffos/fluffos#568]
json_decode("")
执行时段错误：请执行 bug 检查详细错误回溯。
........档案：/adm/kernel/simul_efun/json.c
........行数：第 138 行
........错误：*Unexpected end of data @ line 1 char 1

**Comment by thefallentree** [comment]
json_decode("\"\"")  == ""

json_decode("") is simply wrong.   even Javascript doesn't allow it.

![image](https://user-images.githubusercontent.com/1256464/72405445-bf314080-370d-11ea-8f01-3b2de0f84eb3.png)
