### ISSUE TITLE
question concerning efun::stat and efun::get_dir

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#571]
Could someone explain to me why ```efun:stat(string path, int flag)```, when given a directory as argument or the flag equals -1, behaves as if we called ```efun::get_dir(path, 0)```?
And why ```efun::get_dir(string path, int flag)``` behaves as if ```efun::stat(path, 0)``` where called for each directory entry when given a directory and ```flag == -1```?

Wouldn't it be more logical if we removed the 2nd argument from ```efun::get_dir``` and changed ```efun:stat``` to simply return the result of the ```stat(2)``` call regardless if it's a file or a directory? We could even extend the functionality and given a ```flag == -1``` ```efun::stat``` would return the filestats for each file matching the given pattern or found in the given directory....

**Comment by thefallentree** [comment]
Adding EFUNS are okay,  removing or changing EFUNS we can not do due to  compatibility reasons
The few options:
1.  Fix documentation.  just click on edit on https://www.fluffos.info/efuns and send in your PR!
2. create an new efun called  stat2() or statEx() and change your code to use that instead.

Whichever is okay by me

**Comment by Shea690901** [comment]
How about we made the change a compile time option, for now defaulting to the old behavior but giving a warning about the change in the future. Then for some driver version in the future switch the default behavior but still ship with the old one giving a stronger warning ifcompiled with that setting and only completely removing the old behavior when reaching an even later driverversion?

**Comment by thefallentree** [comment]
in v2019 we are not planning to add any more compile time options, so if we want we have to create new efun for it, and individual mud can use sefum to override if they so choose
