### ISSUE TITLE
general test issues

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#572]
The tests should be checked and secured by ```#ifdef __PACKAGE_XXX__```
I noticed that with current master branch several tests fail because of parse errors when the driver is compiled with only core and ops package...
Among those I especially noticed (but not only those!):
- /single/tests/compiler/utf8.c
- /single/tests/efuns/send_nullbyte.c

**Comment by thefallentree** [comment]
will not fix, there are too many things and it is of relatively low value to support customized build.
