### ISSUE TITLE
hidden dependencie

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#576]
I'm nearing a point with #465, where hidden dependencies between packages and/or core driver are disruptive to further work...

As such I've just taken a closer look (a dozen recompiles with different selected packages) and found only one dependency remaining:
package/develop depends on package/sockets...

**Comment by thefallentree** [comment]
The reason that I migrated core / ops /develop out of main driver was in order to separate api code, but they could moved back, since it is highly unlikely that things could work without those enabled at all time.

**Comment by thefallentree** [comment]
fix merged, keep up the good work!

**Comment by Shea690901** [comment]
I think we should keep even core and ops as seperate packages which just can't be deselected.
That would keep all efun-supplying sources symetrically ;)
