### ISSUE TITLE
ANSI Escape codes introducing whitespace?

### ISSUE THREAD

**Issue by Penniman** [fluffos/fluffos#580]
I have just compiled the latest v2019 driver, ac3d24b, and have noticed that ~~every PinkFish code~~ _ANSI Escape sequences, chr(27),_ in a string is now introducing a whitespace character in the output.

Has anybody else noticed this?

I am sorry that I don't have full details yet, I am working on it...  The terminal_colour() function in src/packages/contrib.cc was changed October 2019 (25954ca) and now assigns **nullptr** where it used to assign **0**.  I do not yet know if that is what is causing my whitespace but that is what I am going to look at first.

EXAMPLE:
```
  "%^RESET%^%^BOLD%^%^YELLOW%^Gurble blat" || "^[0m^[1m^[33mGurble blat"
  "   Gurble blat"
```

where ^ represents the ANSI Escape character, chr(27).

**Comment by thefallentree** [comment]
Thanks for the feedback. I don’t think terminal_colour() changes matters, this is the first time I see pink fish code, can you include an full example on how do you observe this? Is is through sprintf()?  Which sounds like an bug introduced in utf8-lization.

Thanks

**Comment by Penniman** [comment]
PinkFish codes are mudlib-specific string-based tokens which are translated into ANSI escape sequences used primarily for changing the foreground and background color of text.

In my example above, "%^RESET%^%^BOLD%^%^YELLOW%^" is transformed (by the mudlib) into the ANSI escape sequences, "^[0m^[1m^[33m" where ^ represents the ASCII Escape character, chr(27).  This sequence resets the foreground/background attributes to their default and then set the foreground to bold yellow.

In my mudlib, if I execute **eval return chr(27)**  I receive " " as output, the Escape character is returned but so is an additional whitespace character.

If I execute **eval return chr(27) + "[33mThis is yellow"** I receive " This is yellow" as output.  The text foreground has been aproproriately changed to yellow but the Escape character still produces an extraneous whitespace character.

**Comment by thefallentree** [comment]
I don't think there is an chr() efun,  it might be an simul_efun defined by your lib, can you check what is the source code for that simul_efun? 

Thanks

**Comment by seikichin** [comment]
how about try #define RESET "\x1b[0m"

**Comment by Penniman** [comment]
> I don't think there is an chr() efun,  it might be an simul_efun defined by your lib, can you check what is the source code for that simul_efun?

`string chr(int asciiCode) { return sprintf("%c", asciiCode); }`

The Escape character, code 27, is one of the Non-Printable Control Codes.

**Comment by Penniman** [comment]
I printed out each of the Non-Printable Control Codes, character codes 1 through 31, and the Escape code, 27, is the only one that results in unexpected whitespace.

The Horizontal Tab (9) and Line Feed (10) codes output the literal strings "\t" and "\n" respectively.  I don't recall if that was the same behavior as older commits or not.  All other codes perform their expected function: the Bell character (7) causes an audible beep and Carriage Return (13)  moves the cursor location to the start of the line.
