### ISSUE TITLE
APPLY_RECEIVE_ENVIRON convert all NEW-ENVIRON options to string

### ISSUE THREAD

**Issue by lostsnow** [fluffos/fluffos#587]
Currently in

https://github.com/fluffos/fluffos/blob/a4488f218f1973bc7497c116806af3cfb3f35f12/src/net/telnet.cc#L310-L324

convert all NEW-ENVIRON options to string by:

```c
sprintf(buf, "%d%s%d%s", ENV_FILLER, values[i].var, 1, values[i].value); 
```

This should not be a correct implementation, because user can not split by these options

For example set user's real ip by NEW-ENVIRON:

```
<IAC><SB><39><0><0>REAL_IP<1>172.22.22.1<IAC><SE>
```

apply `receive_environ` received:

```c
"30REAL_IP1172.22.22.1"
```
`30` (`ENV_FILLER` `0x1e`) and `1` before ip (172.22.22.1) can not be converted to string

Also I found a correct implementation in fluffos 2.x:

https://github.com/quixadhal/fluffos/blob/3b54c21b045edae45b7df732d3f7c958a19f84a9/src/comm.c#L1182-L1202

```c
    case TELOPT_NEW_ENVIRON :
    {
        int j, k;
        char env_buf[BUF_SIZE];
        j = 0;
        k = 1;
        while(ip->sb_buf[k] > -1 && k < (ip->sb_pos - 1)){
            k++;
            if(!(ip->sb_buf[k])) env_buf[j] = ENV_FILLER;
            if(ip->sb_buf[k] == 1) env_buf[j] = 1;
            if((ip->sb_buf[k] > 31)){
                env_buf[j] = ip->sb_buf[k];
            }
            if(env_buf[j]) j++;
        }
        env_buf[j] = 0;
        copy_and_push_string(env_buf);
        apply(APPLY_RECEIVE_ENVIRON, ip->ob, 1, ORIGIN_DRIVER);
        break;


    }
```

**Comment by lostsnow** [comment]
https://github.com/fluffos/fluffos/commit/a901c645fdd7691b22cd5c015913dc2c9daddadd#diff-af42001b0081d87ee1224909166815f7

The code changed in this commit

**Comment by thefallentree** [comment]
this apply will be changed to pass in as buffer
