### ISSUE TITLE
v2019-mingw64 crash

### ISSUE THREAD

**Issue by suimengjushi** [fluffos/fluffos#592]
Accepting telnet connections on 0.0.0.0:4000.
Accepting telnet connections on 0.0.0.0:6000.
Initializations complete.

[Thread 11320.0x2f10 exited with code 0]
[Thread 11320.0xfcc exited with code 0]
[Thread 11320.0x2204 exited with code 0]
[New Thread 11320.0x2f84]
[Thread 11320.0x2f84 exited with code 0]
[Thread 11320.0x21c0 exited with code 0]
[New Thread 11320.0x2c10]
[Thread 11320.0x2c10 exited with code 0]
[New Thread 11320.0x2ff8]
[Thread 11320.0x2ff8 exited with code 0]
[New Thread 11320.0x2a70]
[Thread 11320.0x2a70 exited with code 0]
[New Thread 11320.0x24f0]
[Thread 11320.0x24f0 exited with code 0]
[New Thread 11320.0x2bb4]
[Thread 11320.0x2bb4 exited with code 0]
[New Thread 11320.0x2d14]
[Thread 11320.0x2d14 exited with code 0]
[New Thread 11320.0xe04]
[Thread 11320.0xe04 exited with code 0]
[New Thread 11320.0x23e0]
[Thread 11320.0x23e0 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004f5dd3 in clean_buf(interactive_t*) [clone .lto_priv.0] (
    ip=0x7be8710) at G:/msys64/home/li/fluffos-master/src/comm.cc:830
830     G:/msys64/home/li/fluffos-master/src/comm.cc: No such file or directory.
(gdb) bt
#0  0x00000000004f5dd3 in clean_buf(interactive_t*) [clone .lto_priv.0] (
    ip=0x7be8710) at G:/msys64/home/li/fluffos-master/src/comm.cc:830
#1  0x00000000004f8a50 in get_user_data (ip=0x7be8710)
    at G:/msys64/home/li/fluffos-master/src/comm.cc:925
#2  0x0000000000649c38 in bufferevent_run_deferred_callbacks_locked ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#3  0x0000000000652bef in event_process_active_single_queue ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#4  0x0000000000653829 in event_base_loop ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#5  0x000000000078500a in main (argc=1884387569, argv=0xc)
    at G:/msys64/home/li/fluffos-master/src/backend.cc:232
(gdb) bt
#0  0x00000000004f5dd3 in clean_buf(interactive_t*) [clone .lto_priv.0] (
    ip=0x7be8710) at G:/msys64/home/li/fluffos-master/src/comm.cc:830
#1  0x00000000004f8a50 in get_user_data (ip=0x7be8710)
    at G:/msys64/home/li/fluffos-master/src/comm.cc:925
#2  0x0000000000649c38 in bufferevent_run_deferred_callbacks_locked ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#3  0x0000000000652bef in event_process_active_single_queue ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#4  0x0000000000653829 in event_base_loop ()
    at G:/msys64/mingw64/include/c++/9.2.0/bits/stl_deque.h:757
#5  0x000000000078500a in main (argc=1884387569, argv=0xc)
    at G:/msys64/home/li/fluffos-master/src/backend.cc:232

**Comment by thefallentree** [comment]
What version this is?
