### ISSUE TITLE
sprintf会对空格进行换行处理

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#600]
eval write(sprintf("%-60=s","西雅图及其科技重镇Kirkland、 Redmond和Bellevue所在地华盛顿州的King County是美国迄今为止新型冠状病毒肺炎大规模暴发的地区。西雅图也是微软总部的所在地。现在微软允许西雅图和旧金山办公室的员工至少在3月9日之前都采取远程工作。"))

printf():
"西雅图及其科技重镇Kirkland、Redmond和
Bellevue所在地华盛顿州的King
County是美国迄今为止新型冠状病毒肺炎大规模暴发的地区。西雅图
也是微软总部的所在地。

中英文之间有空格的，或者英文之间有空格的都出问题

**Comment by seikichin** [comment]
printf("%*.*s",-7,2,"foobarbloh")  
should returns "fo     "
but now it returns "fo"

**Comment by seikichin** [comment]
returns "fo     "

**Comment by thefallentree** [comment]
issue solved, should not pass in -7 but put - in format string instead
