### ISSUE TITLE
LIMA Support?

### ISSUE THREAD

**Issue by staun** [fluffos/fluffos#625]
Hey,

Any chance this driver could get support for Lima mudlib? It requires parser support which I cannot seem to find in this branch. We have quite a few MUDs that are effectively unable to use this driver since it doesn't support Lima.

[local_options.txt](https://github.com/fluffos/fluffos/files/4438971/local_options.txt)

Added my local_options so you can see what I'm compiling currently. I can only hope it's a small effort to do, and I'd like to participate in testing and reporting issues I find.

Cheers!

**Comment by thefallentree** [comment]
The Lima lib should be brought forward, not stuck in the old state forever, I'm happy to start an repo to maintain an version that will work with fluffos v2019. 

PACKAGE_PARSER is now fixed and fully functional in v2019, so there shouldn't be big blockers , just no one has actually requested it.

**Comment by staun** [comment]
Fantastic! How would I best get you feedback on my results? I'm an IT professional, so open to whatever you suggest. I have a feeling this may be a bit of a process ... :-)

**Comment by thefallentree** [comment]
If you want, let me add you the organization, you can setup an repo with lima code , and we will work together on that repo to address any issues you find.

**Comment by staun** [comment]
All happy with that setup :-)

**Comment by thefallentree** [comment]
lima lib is live on https://github.com/fluffos/lima
