### ISSUE TITLE
NIghtmare 3 Fluffos 3.0 modifications

### ISSUE THREAD

**Issue by evilmog** [fluffos/fluffos#631]
Hi There,

Deadsouls under fluffos 3 has a number of bugs and I'm not a fan of dead souls anyways. I have a game on gurbalib but I'd like to rewrite for nightmare 3, unless you can port gurbalib to run on fluffos.

There isn't much in the way of usable english libs unless somebody is willing to translate into english one of the fine libs made in China.

Nightmare 3 under older fluffos can be found here http://dead-souls.net/files/nightmare3_fluffos_v2.zip  I haven't managed to get that version of fluffos to compile in a while though but like the lib for nostalgic reasons.

A lot of muds out there are nightmare derived and I'd like to get a minimalist nightmare variant working.

**Comment by thefallentree** [comment]
Sure, let’s follow the Lima model and setup an repo for nightmare.

It shouldn’t be too hard.

**Comment by seikichin** [comment]
https://github.com/openshadowgate/shadowgate.git
I am not sure if this mud is based nightmare but it's an active mud which use fluffos2019

**Comment by thefallentree** [comment]
I've completed an basic conversion of nightmare3 at https://github.com/fluffos/nightmare3

Give it a try,  pls open issues on that repo if you meet diffculities
