### ISSUE TITLE
strwidth() of escape chars returns the width including escape chars

### ISSUE THREAD

**Issue by staun** [fluffos/fluffos#633]
Hey,

I tried to stop using using terminal_colour() efun which has certain issues with escape codes. This is my sefun overriding terminal_colour()
```
//:FUNCTION terminal_colour
//Override of efun to avoid some driver issues.
string terminal_colour(string str, mapping m, int wrap, int indent)
{
    str = efun::terminal_colour(str,m,wrap,indent);
    str = replace_string(str, "\e[0;10m", "");
    str = replace_string(str, "\e[49;49m", "");
    return str;
}
 ```

So as a started I changed my M_ANSI module to:
```
//:FUNCTION colour_strlen
//colour_strlen(s) gives the length of the visible portion of s.  Colour
//codes (e.g. %^GREEN%^) are ignored.
int colour_strlen(string str)
{
	//return strlen(terminal_colour(str, ANSI_D->query_translations()[1]));
	return strwidth(str);
}
```
(Notice the commented out line)

But I found that strwidth() returns the wrong size as well as terminal_colour() did before I did the sefun override!

Try:
```
@ write(strwidth("Hello\e[10m\e[49;49m\n"))
50
```
(@ is eval on LIMA)
Strlen returns 190 length on same string which is also... bad :)

**Comment by thefallentree** [comment]
I just tested on imud.fluffos.info, 

![image](https://user-images.githubusercontent.com/1256464/79792143-455bb500-8303-11ea-92eb-55b141f906d1.png)

this looks correct to me.

![image](https://user-images.githubusercontent.com/1256464/79792192-56a4c180-8303-11ea-8c6c-1fd59177e5c1.png)

**Comment by thefallentree** [comment]
I think your "@" script is just printing out an "0" as the result of the eval.  If you remove write() it should give you correct value.

**Comment by staun** [comment]
Yeah, you're right, but doesn't fix my issue.

This is without strwidth()
![image](https://user-images.githubusercontent.com/5774045/79794917-63e99c80-8353-11ea-9c9f-0688ccc87217.png)

This is with strwidth()
![image](https://user-images.githubusercontent.com/5774045/79794963-7e237a80-8353-11ea-981d-b6baa2f8ec6c.png)

I'll see if I can figure out what's causing this then. Strwidth() is clearly doing something bad, but could be ANSI system in LIMA.

**Comment by staun** [comment]
Got it, I thought strwidth() stripped out the ansi codes (%^RESET%^ etc.) as well, but only if they've been translated to escape codes.  Slightly less useful then strwidth() as I need to pass it through terminal_colour() first then to strip away the ANSI tags.

**Comment by thefallentree** [comment]
Yeah, strwidth only works with real ansi codes, not the substitution string, that is more like an lib thing.  

in your case, if you are looking to format in column, you can look to sprintf table mode, may or may not be easier for you.

**Comment by staun** [comment]
Yeah, that's built into the ansi module, but requires an accurate strlen() disregarding colors.

**Comment by thefallentree** [comment]
why not just do an sefun override for strwidth to strip PinkFish code first?

**Comment by staun** [comment]
Yeah, I could, but I wanted to cut down on transactions inside the lib. Nevermind, I misunderstood how strwidth() worked the other day when you talked about it :-)

**Comment by thefallentree** [comment]
Yeah, sorry, in general, I prefer to enable people to write more versatile LPC code, so driver don't bring incompatible changes, if you are interested we could discuss how we can provide an LPC version of terminal_colour() that is part of the stdlib and remove that efun instead.

If we need add new efun for fast string replacement, we could do that,  also. there is now pcre_replace() which could be pretty useful to implement it.

**Comment by staun** [comment]
I think there could be a huge performance gain here potentially since every single string delivered to a user is parsed through terminal_colour with a replacement mapping. I'm sure that can done more efficiently. At least we should aim for efficiency here :)
