### ISSUE TITLE
./src/packages/external/ is missing CMakeLists.txt

### ISSUE THREAD

**Issue by Penniman** [fluffos/fluffos#636]
The external package directory, ./src/packages/external/, is missing CMakeLists.txt which causes the driver build process to fail when running with -DPACKAGE_EXTERNAL=on.

On my system I created this file with the following content which was based off of what I found in other similar files:
```
option(PACKAGE_EXTERNAL "external package" ON)

if(${PACKAGE_EXTERNAL})
    add_library(package_external STATIC
        "external.cc"
        )
endif()
```

**Comment by thefallentree** [comment]
Yeah, but I don't think this package is working yet

**Comment by Penniman** [comment]
It was working with v2019 up until just recently.  I had to create the CMakeLists.txt and add the missing #include <event2/event.h> to external.cc first.

It just stopped working for me recently when I recompiled the driver a few days ago with the latest v2019 commits.

**Comment by thefallentree** [comment]
hmm, no problem, let me take a look.
