### ISSUE TITLE
是否有必要做一个官方的 Docker 镜像？

### ISSUE THREAD

**Issue by dzpao** [fluffos/fluffos#640]
我看到群里有人讨论，建议做一个 Docker 镜像，目前其实已经有好几个了，但因为没有和本仓库做集成，所以内容不权威。
如果有必要的话，我可以试着做一个，通过 GitHub Actions 自动 push 到 Docker Hub 上去，以确保镜像内容的权威性和及时性。

**Comment by oiuv** [comment]
我已经在docker上注册了fluffos这个ID，可以转给官方做docker镜像。

**Comment by dzpao** [comment]
@oiuv 我还说呢，我刚才去注册已经被占了，还好是自己人。

**Comment by oiuv** [comment]
> @oiuv 我还说呢，我刚才去注册已经被占了，还好是自己人。

先占着，安全，给官方准备着，被不知道的人注册才是麻烦了。

**Comment by thefallentree** [comment]
可以整 而且有另外一个哥们已经做好了

**Comment by flw-cn** [comment]
做好了是啥意思，就是说现在不用做了吗？还是说可以整一个？

**Comment by dzpao** [comment]
做好了是说现在不用做了吗？

**Comment by shawn4096** [comment]
支持官方docker

**Comment by thefallentree** [comment]
把docker项目贡献一下吧

**Comment by oiuv** [comment]
> 把docker项目贡献一下吧

怎么贡献啊？我可以把docker上的fluffos这个账号和密码提供出来，目前上传的镜像是我弄的这个项目：https://github.com/MudRen/docker_fluffos

感觉还可以优化，只是没想好怎么弄，可以的话我先把项目转移到fluffos下？

**Comment by Hsins** [comment]
> > 把docker项目贡献一下吧
> 
> 怎么贡献啊？我可以把docker上的fluffos这个账号和密码提供出来，目前上传的镜像是我弄的这个项目：https://github.com/MudRen/docker_fluffos
> 
> 感觉还可以优化，只是没想好怎么弄，可以的话我先把项目转移到fluffos下？

有了這個 Docker Image 可以配合 GitHub Actions 在當前源代碼的這個項目倉庫綁定自動編譯，並發布編譯完成的執行檔到 release 中，可以省去不少麻煩

**Comment by thefallentree** [comment]
https://github.com/fluffos/fluffos/pkgs/container/fluffos
