### ISSUE TITLE
复杂点的json文件会卡死

### ISSUE THREAD

**Issue by lonag** [fluffos/fluffos#641]
使用std/json.c解析json文件
[item.zip](https://github.com/fluffos/fluffos/files/4823738/item.zip)

**Comment by lonag** [comment]
我怀疑是里面包含中文的问题，可能不是json太复杂，或许是中文utf8解析的问题

**Comment by lonag** [comment]
再试了下，简单的json，包含中文不会有问题

**Comment by thefallentree** [comment]
Will fix this week
