### ISSUE TITLE
got this error message at very last step

### ISSUE THREAD

**Issue by yiwangdev** [fluffos/fluffos#642]
[ 98%] Linking CXX executable driver
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/driver] Error 1
make[1]: *** [src/CMakeFiles/driver.dir/all] Error 2
make: *** [all] Error 2

**Comment by thefallentree** [comment]
You can either turn off -DPACKAGE_CRYPTO=OFF

Or you need to install OpenSSL through homebrew and set OPENSSL_ROOT_DIR during cmakr
