### ISSUE TITLE
PACKAGE_COMPRESS参数定义问题

### ISSUE THREAD

**Issue by icerxkx** [fluffos/fluffos#656]
编译fluffos2019的时候，由于mud cpu负载过高，而带宽富裕，所以想不支持mccp压缩，于是
#undef PACKAGE_COMPRESS
#undef SAVE_GZ_EXTENSION 
但编译不过，提示：

[ 91%] Building CXX object src/CMakeFiles/libdriver.dir/vm/internal/base/program.cc.o
/root/fluffos/src/vm/internal/base/object.cc:1471:52: error: ‘SAVE_GZ_EXTENSION’ was not declared in this scope; did you mean ‘SAVE_EXTENSION’?
 1471 | static const int SAVE_EXTENSION_GZ_LENGTH = strlen(SAVE_GZ_EXTENSION);

还必须得
#undef PACKAGE_COMPRESS
#define SAVE_GZ_EXTENSION ".o.gz"
才能编译通过，但这样编译出来的fluffos玩家客户端显示仍然支持mccp协议。

**Comment by thefallentree** [comment]
already fixed.
