### ISSUE TITLE
add virtual_start apply in fluffos for migration of incredibly old mudos mud.

### ISSUE THREAD

**Issue by crius-al** [fluffos/fluffos#659]
I can't fix this myself since I don't know how. Thefallentree suggested I create this issue.

https://forum.fluffos.info/t/virtual-object-name-duplicates-an-existing-object-name/1444/21?u=crius-al
"BTW: it seems we could easily add this “virtual_start” apply in Fluffos too, this way you wouldn’t have to simulate this in LPC ,which would eliminate this weird issue of recursive loading object , since driver will take care calling it after the object is fully constructed"

**Comment by thefallentree** [comment]
fixed in #658
