### ISSUE TITLE
建议加入对副本任务的多核支持

### ISSUE THREAD

**Issue by icerxkx** [fluffos/fluffos#679]
目前单核的运行机制对于人数较多的Mud来说，消耗CPU过高，巫师很大一部分精力花费在如何优化代码，如何节省CPU上，出于性能考虑也无法随意发挥自己的想象力，实现相应的设计。我们的Mud，使用阿里云高主频型主机，在线500多人，单核基本在90%以上，经常卡在100%，然而四核中有三个闲置，整体CPU占用只有25%。

虽然Mud的机制确实不好实现多核支持，但对于常见的副本类型任务来说，由于进入副本的人与外界联系隔绝，除了聊天没有别的交流接触通道，应该可以支持一个特别的lpc定义方式，这个定义下的区域、角色和物品由一个单独的核来运行。比如某个大型群体任务或者频繁并发执行的单人任务，进入副本后整体转到另外一个核上单独跑。这样可以大大减轻主CPU的压力，对于编写大型群体任务的性能要求也大为降低。

对驱动底层了解不多，只是提出一个不成熟的想法，希望能成为现实。

**Comment by LaoZhongGu** [comment]
还不如考虑直接换语言重写了，用Java或者Go都是可以的，CPP啥的也行，外加skynet都可以。

**Comment by seikichin** [comment]
重写的任务就交给你了加油给你一年时间

**Comment by thefallentree** [comment]
这里并不适合讨论这种没有实际行动项目的问题，性能问题有 tracing 解决，网络单核问题有多核化网络层来解决， 副本问题现在的想法是做LPC 的 RMI 。针对具体问题可以具体分析。
