### ISSUE TITLE
关于sockets.cc的一些疑问

### ISSUE THREAD

**Issue by iamwlj** [fluffos/fluffos#711]
void f_socket_bind(void) {
  int i, fd, port, num_arg = st_num_arg;
  svalue_t *arg;
  char addr[ADDR_BUF_SIZE];

  arg = sp - num_arg + 1;
  if ((num_arg == 3) && (arg[2].type != T_STRING)) {
    bad_arg(3, F_SOCKET_BIND);
  }

  fd = arg[0].u.number;
  get_socket_address(fd, addr, &port, 0);

  if (VALID_SOCKET("bind")) {
    i = socket_bind(fd, arg[1].u.number, (num_arg == 3 ? arg[2].u.string : nullptr));
    pop_n_elems(num_arg - 1);
    sp->u.number = i;
  } else {
    pop_n_elems(num_arg - 1);
    sp->u.number = EESECURITY;
  }
}

为什么在bind的时候，要get_socket_address来查询remote的地址信息？bind的时候，r_addr根本没有值的吧？
sockets.cc里还有其他的get_socket_address也有点没看明白。
请指教了！

**Comment by thefallentree** [comment]
这段代码是将 传入的 ”127.0.0.1.8888” 字符串转换为 struct sock_inaddr 结构体。

**Comment by thefallentree** [comment]
不过这段代码好像的确有点问题 没有必要调用 可能是之前代码合并的遗留问题
