### ISSUE TITLE
contrib:zonetime() should return a code or error if invalid timezone string passed

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#716]
The zonetime() efun should result in either an error or, more ideally, a result code (0 or -1) if the timezone string that is passed is not valid.

Presently, it returns UTC. This is not useful for determining if an operation was successful, since `zonetime( "tabby cat", time() );` looks like `zonetime("Europe/London", time());`

**Comment by thefallentree** [comment]
this is just the default behavior by glibc , it is not possible to change without using another set of library (for example c++20's new calendar library)
