### ISSUE TITLE
missing efun each()?

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#720]
Was looking through the efuns and noticed that there's one called `each()`. 

I tried to run a sample given the documentation found here: [https://www.fluffos.info/efun/mappings/each.html#gsc.tab=0](https://www.fluffos.info/efun/mappings/each.html#gsc.tab=0)

However, FluffOS is saying `Undefined function each`.

I did a grep for the function f_each and couldn't find it.

**Comment by thefallentree** [comment]
just use foreach(x, y in map) {}

**Comment by gesslar** [comment]
Yes, I know how to use foreach. I'm merely pointing out that you have
documentation for an efun that I couldn't find.

**Comment by thefallentree** [comment]
this is now deleted.
