### ISSUE TITLE
Help porting an old nm3/4 based mudlib to fluffos 2019

### ISSUE THREAD

**Issue by evilmog** [fluffos/fluffos#724]
Hi There, 

I've got an older nightmare 3 ish mudlib called colony that I'm trying to port over to v2019, I did a comparison of the nightmare 3 lib and it looks like the Secure dir is in /adm and SimulEFun is different enough, do you have a guide for how to make older libs v2019 or v2017 compatible?

**Comment by gesslar** [comment]
@evilmog Hi man, I've responded to you in the support chat, but you'll want to check out the 2019 guide here [https://www.fluffos.info/build.html#gsc.tab=0](https://www.fluffos.info/build.html#gsc.tab=0). But you're free to hit me up on that chat or in Discord. I can help.

**Comment by thefallentree** [comment]
while this is being resolved on gitter,  I can put https://forum.fluffos.info/t/common-lpc-migration-issues-v2019/1341  here for prosperity
