### ISSUE TITLE
set_heart_beat(0) delay until next round

### ISSUE THREAD

**Issue by Mordred-Dawn** [fluffos/fluffos#738]
Currently set_heat_beat(0) sets a removal flag which removes the object's heart_beat during the next call_heart_beat.

This means that any calls to set_heart_beat(i), i!=0, during the same round as a set_heart_beat(0) are overrided. Ignoring these set_heart_beats in the stack results in the complete inability to deal with a set_heart_beat(0) anywhere in an inherit chain without using a bizarre call_out to restart the heart_beat after the round finishes.. This work around completely nullifies the utility of heart_beat.

Is this intended behavior? If so there should be a way to remove the flag so that stack priority can be maintained on a case-by-case basis.

**Comment by thefallentree** [comment]
Good call, it seems like a mistake, I can fix this behavior so that the last call takes effect

**Comment by Mordred-Dawn** [comment]
Easily reproducable: 

This will tick for 1 heartbeat after create; then shut off regardless of the second call to set_heart_beat()
```
void create()
{
   set_heart_beat( 1 ) ;
}

void heart_beat()
{
   set_heart_beat(0);
   set_heart_beat(1);
}

```
