### ISSUE TITLE
New behavior for function_exists

### ISSUE THREAD

**Issue by tarik-dawn** [fluffos/fluffos#763]
In the newest release the efun 'function_exist( str , ob )' has new behavior. Rather than returning the base_name of the inherited object containing the function 'str' it always simply returns 'base_name(ob)' if the function exists.

**Comment by silbago** [comment]
Why ? We already know 'ob' and I use it to find file name of the file having this function.

**Comment by tarik-dawn** [comment]
Exactly! That is why I opened this as an issue to find out if the new behavior was intentional.

**Comment by silbago** [comment]
Sounds like something I would have done by mistake :D
