### ISSUE TITLE
Passing function with non-existent local as parameter crashes driver 

### ISSUE THREAD

**Issue by jalbright015** [fluffos/fluffos#773]
While doing some testing I came across this crasher.  I was able to shorten it and consistently replicate it in testsuite.

`eval objects(function(){if ($1) return 1;})`

The above crashes with this error:
`******** FATAL ERROR: Tried to push non-existent local`

It is not specific to objects() and can be replicated with other functions.

**Comment by thefallentree** [comment]
well, interesting, AFAIK one shouldn't be able to use $1 outside closures, this is pretty interesting.

Nonetheless, I will try to fix this
