### ISSUE TITLE
Windows下出现 Segmentation fault当掉的问题

### ISSUE THREAD

**Issue by junbiaolee** [fluffos/fluffos#779]
![图片](https://user-images.githubusercontent.com/16464217/113648189-c94ab080-96be-11eb-802f-a47d9427fb0e.png)
追踪到让driver当掉的是在这里if (!present("lingpai", user) ，但是同样的一份东西，我在MAC下就没这个问题

**Comment by junbiaolee** [comment]
![图片](https://user-images.githubusercontent.com/16464217/114113530-6ef55e00-9911-11eb-9641-fceb8f3a1525.png)
WIN下真的是有BUG，我用雪风适配好的炎黄MUD在WIN跑，执行give就马上当掉出来的

**Comment by thefallentree** [comment]
can't reproduce.
