### ISSUE TITLE
可否考虑增加curl和http api功能？

### ISSUE THREAD

**Issue by fisherwei** [fluffos/fluffos#806]
我这个需求不知道是否有些小众，设想是这样的：

mud通过一个curl函数调用一个http（restful） api，返回json或者其他string来实现和现有系统的集成（比如论坛）。
同时，可以对外暴露一些http api，方便现有系统对游戏内数据进行修改（比如充值）。

**Comment by oiuv** [comment]
这个需求不算什么问题吧？使用socket就能实现，你访问 https://mud.ren:8080 测试看看。其中生成二维码的指令 qrcode 是网页API实现的，chat @ivy help 这个机器人功能也是网页API实现的。

**Comment by thefallentree** [comment]
fixed by fixing PACKAGE_EXTERNAL
