### ISSUE TITLE
Feature request: new applies in interactive for idle start and idle stop

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#813]
It would be nice to have applies in interactive called `void idle_start()` and `void idle_stop(int)` where the argument to idle_stop is the time they were idle in seconds.

**Comment by oiuv** [comment]
我个人感觉没有这个必要，你发呆的标准是多长时间？query_idle()可以返回一个玩家的发呆时间，我个人感觉结合heart_beat()和query_idle()可以满足功能需求。

**Comment by thefallentree** [comment]
Not sure if we need this in driver level. Lib can track user command in executions too.
