### ISSUE TITLE
增加一个启动配置选项，可以忽略参数 warning的

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#834]
增加一个启动配置选项，可以忽略参数错误提示，免得重新编译

**Comment by oiuv** [comment]
这个是自己在log_error这个apply中怎么写的问题吧，这是要从代码上解决的，为什么要动驱动配置呢？

**Comment by thefallentree** [comment]
I am going to introduce new programs  so we can suppress different kind of errors.
