### ISSUE TITLE
Unable to compile driver when -DPACKAGE_DB_SQLITE is enabled

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#847]
After pulling latest commit, attempting to compile with the following

`cmake .. -DPACKAGE_MUDLIB_STATS=0 -DPACKAGE_DB=1 -DPACKAGE_DB_SQLITE=1 -DPACKAGE_EXTERNAL=0 -DPACKAGE_CRYPTO=1`

During compilation, receive this error:
```
/frogdice/thresh/fluffos/src/packages/db/db.cc: In function ‘void f_db_connect()’:
/frogdice/thresh/fluffos/src/packages/db/db.cc:313:5: error: duplicate case value
  313 |     case USE_SQLITE3:
      |     ^~~~
/frogdice/thresh/fluffos/src/packages/db/db.cc:306:5: note: previously used here
  306 |     case USE_MYSQL:
      |     ^~~~
```

**Comment by seikichin** [comment]
edit the cmake list 
set(PACKAGE_DB_SQLITE "3" CACHE STRING "DB Type for SQLITE")

**Comment by gesslar** [comment]
> edit the cmake list
> set(PACKAGE_DB_SQLITE "3" CACHE STRING "DB Type for SQLITE")

Exact same error.

**Comment by gesslar** [comment]
Fixed compilation error by reverting above suggestion and compiling with the runtime option `-DPACKAGE_DB_SQLITE=3`
