### ISSUE TITLE
Feature request: please convey to the client upon connection the character encoding

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#866]
Some clients, during negotiation, will accept notification that the server uses UTF-8 and will switch the client's encoding to match.

Please implement during connection the telnet charset negotiation.

**Comment by gesslar** [comment]
For example, BeipMU

https://github.com/BeipDev/BeipMU/blob/master/Protocols/Telnet.cpp

**Comment by oiuv** [comment]
yes, wel need this. i think can add an efun and an apply，one send Protocol, one receive response

**Comment by vadi2** [comment]
Documentation - https://mudletwiki.pkuxkx.com/w/Manual:Supported_Protocols#Encoding

**Comment by gesslar** [comment]
Have submitted a PR for this https://github.com/fluffos/fluffos/pull/868
