### ISSUE TITLE
Feature Request: libcurl

### ISSUE THREAD

**Issue by justinm** [fluffos/fluffos#874]
Being able to call HTTP(S) web servers is a must in the modern day. Though this can be somewhat emulated with sockets, SSL isn't supported and it can be nasty to get right. Would you consider adding libcurl for supporting calling HTTPS endpoints from inside the MUD?

**Comment by oiuv** [comment]
感觉有了`external_start`的方式，这个需求可以结束了。

**Comment by thefallentree** [comment]
no longer in consideration , the recommendation is to use curl through PACKAGE_EXTERNAL
