### ISSUE TITLE
strwidth() return 1 with (中文特殊符号、制表符、数学符、俄文、希腊文等)

### ISSUE THREAD

**Issue by nnxdie** [fluffos/fluffos#887]
eval write(sprintf("%d\n", strwidth("△") ));
1
eval write(sprintf("%d\n", strwidth("◇") ));
1
eval write(sprintf("%d\n", strwidth("□") ));
1
eval write(sprintf("%d\n", strwidth("б") ));
1
eval write(sprintf("%d\n", strwidth("β") ));
1
eval write(sprintf("%d\n", strwidth("Ⅰ") ));
1
eval write(sprintf("%d\n", strwidth("∏") ));
1
eval write(sprintf("%d\n", strwidth("┍") ));
1
eval write(sprintf("%d\n", strwidth("─") ));
1
...etc

以上这些类别的符号等在中文显示中应该占2个英文字符宽度

**Comment by thefallentree** [comment]
These are considered "East Asian Ambitious width" , the driver default to them as 1 width for now.
