### ISSUE TITLE
external_start短时间多次调用外部命令引起driver的cpu占用飙升

### ISSUE THREAD

**Issue by icerxkx** [fluffos/fluffos#904]
利用external_start调用bash，再调用其他命令
一秒调用5次的时候，driver的cpu占用大概提升20%左右
调用记录如下（python3是bash的参数 ）：
![SLRBYG_D0KYGN$}UM}84XOC](https://user-images.githubusercontent.com/37806358/181045915-b2df7317-3a56-46a1-ac63-f68e5890a26c.png)
cpu记录如下
![VW@P@ _T{J5{V9U@(LU$68](https://user-images.githubusercontent.com/37806358/181046244-34592c49-1228-45c3-909a-f5cb7b213320.png)
没有记录当时的top，只找到了系统的命令数调整记录，可以从中看到driver占用的cpu飙升，当时调用的频率大概是每秒7-10次。观察10分钟左右后发现无好转就撤销了更新，CPU也恢复正常了。

**Comment by oiuv** [comment]
应该是僵尸进程的后遗症？

**Comment by icerxkx** [comment]
> 应该是僵尸进程的后遗症？

不完全是。
这个贴是说调用external_start频率高了引起driver cpu负载变高，可能是fork效率问题。停止external_start就好了。
僵尸进程那个贴的原因大概是因为收尾不完全，导致僵尸进程积累越来越多，到后来即使没有external_start的时候，driver cpu也会保持在高位。

**Comment by oiuv** [comment]
windows系统下好像没这些问题
