### ISSUE TITLE
(疑似)多条件合并filter_array引起宕机

### ISSUE THREAD

**Issue by icerxkx** [fluffos/fluffos#906]
![N%2`YS})~G3~)%RVTKYPTJ3](https://user-images.githubusercontent.com/37806358/181052772-b7448d97-e24f-4d1a-97b2-60ac8e611a3b.png)
上文两种写法，左侧合并filter条件environment时，2天内引起4次宕机，改回右侧写法后恢复正常。

三次宕机记录如下：
![`7WW0X~BH_2HO S NM78$G9](https://user-images.githubusercontent.com/37806358/181053252-5cffcf01-adbf-40d4-85c0-fbac8346c407.png)
是在执行objects()时宕机

另外一次是在执行filter时宕机，如下：
![~}27WSW@M2NY}D6}REN` $7](https://user-images.githubusercontent.com/37806358/181053462-07e4add1-014e-4a06-94a1-776bb2316925.png)

gdb调试core的记录如下：
![CR_4F@3G{{S$HI72V8PQW%4](https://user-images.githubusercontent.com/37806358/181053809-300eeb88-6c1f-4818-8b46-95b61002bc90.png)
![%QJD3ZUB4R4)O{6{VT{J{BS](https://user-images.githubusercontent.com/37806358/181053856-20ff48c3-23d0-4c62-b8f3-01f8511ef9c5.png)

可以看出是regular_check()调用objects()时出现的问题
疑似bug，仅供参考。。。。

**Comment by carl-lucas** [comment]
The driver bug still needs to be addressed, but here is something to try.

You can give a functional argument to objects(), which will be evaluated
with each object - it will act exactly like the filter_array() call. Like
so:

all_livings = objects((: $1 && $1->is_character() && environment($1) :));

Also, if you can be sure that is_character() is only true if the object
inherits a certain file, you can use inherits(), which will run MUCH
faster, especially if you have a lot of objects:

all_livings = objects((: $1 && inherits("/path/to/character_inheritable",
$1) && environment($1) :));

Good luck!

**Comment by icerxkx** [comment]
Good advice! 
Thank you!

**Comment by icerxkx** [comment]
补充：不用多条件合并filter_array也宕机，原因相同，只是频率小了许多，这是上次发帖之后第一次宕机。
![L@3WQS)Y~EZ1DLX`0L(VGJU](https://user-images.githubusercontent.com/37806358/182066514-79a9d1a2-ace4-424f-ad07-310b2d4311b5.png)
相关代码虽然和上次不是同一文件，但仍然是调用objects()时宕机：
![TAIB4BU~1S50_}~I E9HVE0](https://user-images.githubusercontent.com/37806358/182067595-2867d64c-83ff-4a61-b607-e76a0364567d.png)
driver是20200703编译的当时最新版本，之前没有出现过类似宕机

**Comment by seikichin** [comment]
空指针了么

**Comment by icerxkx** [comment]
看着像list[i]空指针，但是list[i]上一行刚访问过，不懂了。。。

**Comment by icerxkx** [comment]
换回原版过了几天也宕机了。。。怀疑还是自己写的efun的锅，先关闭了。。
