### ISSUE TITLE
external_start导致defunct进程

### ISSUE THREAD

**Issue by icerxkx** [fluffos/fluffos#907]
external_start运行完毕之后系统中留下defunct进程，如图：
![T0Z48RA{K%2QEZ6P$C5~XFV](https://user-images.githubusercontent.com/37806358/181703712-a07895c9-0a90-4cf1-a244-16faaf401fe9.png)
无法直接kill，只能等待driver重启才能彻底消除

**Comment by icerxkx** [comment]
补充：僵尸进程会提升driver进程自身的cpu消耗。mud运行5天，僵尸进程达到8000时，driver的cpu占用比以往大约提升了30%

**Comment by oiuv** [comment]
测试了，的确如此。
