### ISSUE TITLE
new() and clone_object() not throwing error on non-existent file

### ISSUE THREAD

**Issue by MonkeyFreeZone** [fluffos/fluffos#914]
Driver version (most recent) v2019, compiled from git pull on 2022-Aug-17
OS version: Ubuntu 22.04.01 (latest) server - no driver compile issues.

Problem:
new() and clone_object() no longer throw an error when used on a non-existent file.

Example:
```
mixed err;
object ob;

err = catch(ob = new("/no/such/file"));
if(err)
{
    write("err\n");
}
else
{
    write("no err\n");
}
if(nullp(err))
{
    write("err is null\n");
}
else
{
    write("err is not null\n");
}
write("typeof(err): " + typeof(err) + "\n");
write("err value: " + err + "\n");
```

Returns the following output:
```
no err
err is not null
typeof(err): int
err value: 0
```

Expected output - similar to previous driver versions:
```
err
err is not null
typeof(err): string
err value: *Error in Loading /no/such/file - file does not exist
```

**Comment by oiuv** [comment]
这个本来就不会返回错误吧？文件不存在会调用`object compile_object( string pathname );`处理，没有就返回0呀。

**Comment by oiuv** [comment]
只有文件存在而且代码有错才会报错。

**Comment by MonkeyFreeZone** [comment]
Thank you for looking.

Currently in the master object:

```
object compile_object(string file)
{
    return 0;
}
```

Because I have not written the virtual object compiler yet.

Changed to this:
```
object compile_object(string file)
{
    if(file_size(file) < 0)
    {
        error("Cannot load a file that does not exist: " + file);
        return 0;
    }
    return 0;
}
```

Gives the expected behavior

**Comment by thefallentree** [comment]
working as intended.

**Comment by thefallentree** [comment]
hmm, this might be due to the recent changes in check_legal_path() .

we gotta add this test case into testsuite
