### ISSUE TITLE
Please confirm that errorp() is not implemented

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#915]
I scanned the source, but couldn't find `f_errorp`, so I presume it's not there. If it is not, I can remove it and mentions of it from documentation.

**Comment by oiuv** [comment]
没有这个efun，至少目前是没有实现这个功能，感觉意义不大，在中文efun文档 https://mud.wiki/Lpc:Efun 我已经明确的移除了errorp()的介绍。

**Comment by thefallentree** [comment]
no errorp()
