### ISSUE TITLE
[FEATURE REQUEST] Add support for Binary Literals

### ISSUE THREAD

**Issue by 11Spades** [fluffos/fluffos#965]
Currently, FluffOS has support for hex literals (0xFFFFFF), but not binary literals (0b11111111).

While binary literals are a fairly obscure feature, they go hand-in-hand with bitwise operations, which FluffOS does support.

Thus, I feel that support for binary literals would be a nice addition to the driver.

**Comment by jalbright015** [comment]
I have added support for binary literals.

```
>eval int sum_bin_literals = 0b101 + 0B110; return sum_bin_literals
11
```

I will write some test cases and will submit a pull request to get this merged.
