### ISSUE TITLE
Setting a TLS port after a regular port prevents driver from starting

### ISSUE THREAD

**Issue by michaelprograms** [fluffos/fluffos#970]
When setting up TLS ports, the config file passed into fluffos needs to have the TLS ports configured prior to regular telnet ports if you are using `external_port_#: ####` format. Using `port number : ####` does not appear to be effected.

## Example config which causes fluffos driver to not startup:
```
external_port_1: telnet 6666
external_port_2: telnet 6667
external_port_2_tls: cert=secure/etc/tls/cert.pem key=secure/etc/tls/key.pem

mudlib directory : /home/mud/game/lib
```
```
Accepting telnet connections on 0.0.0.0:6666.
Processing TLS config for port 6667...
init_user_conn: bind error: Address already in use.
```

## Example config which boots up correctly:
```
external_port_1: telnet 6667
external_port_1_tls: cert=secure/etc/tls/cert.pem key=secure/etc/tls/key.pem
external_port_2: telnet 6666

mudlib directory : /home/mud/game/lib
```
```
Processing TLS config for port 6667...
Accepting telnet(TLS) connections on 0.0.0.0:6667.
Accepting telnet connections on 0.0.0.0:6666.
Initializations complete.
```

**Comment by thefallentree** [comment]
I don't think this bug is valid:  as you can see testsuite config

![image](https://github.com/fluffos/fluffos/assets/1256464/1d8b1f5b-2cc0-4aef-9195-64e505258c07)


and 

![image](https://github.com/fluffos/fluffos/assets/1256464/b60380a8-3d86-48b9-a80f-1d89a19bea19)



both bootup correctly

**Comment by michaelprograms** [comment]
👍 I can't replicate anymore, it must have been something OS related.
